// catalog.js — the exercise catalogue of the gym this app was built for, 151 movements
// across 13 categories. Browse it under Exercises and add what you actually train; nothing
// here is in your library until you tap Add.
//
// Names, categories and levels were captured from the gym's own catalogue and are used
// verbatim. The unit for each movement was classified by qwen2.5-coder:14b running locally,
// then checked: it corrupted 24 names by reading UTF-8 as Latin-1 and quietly dropped a
// letter from "Klimmzüge", so ONLY its unit choices were kept and every name comes from the
// source. Two of its calls were corrected by hand — box jumps are counted rather than held,
// and the assisted pull-up machine has a weight stack.
//
// `unit` is only a sensible default. Change it per exercise under Exercises — a machine set
// in Stufe rather than kilograms is one tap away.

export const CATALOG_GROUPS = ['Brust', 'Rücken', 'Schultern', 'Beine', 'Bauch', 'Arme', 'Cardio', 'Stretching', 'Ganzkörper', 'Hüfte', 'Erwärmung', 'Loaded Carry', 'Lifting'];

export const CATALOG = [
  { name: 'Beugestütz mit Hilfe - Assisted dip machine', group: 'Brust', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Brustpresse - Chest press machine', group: 'Brust', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Fly', group: 'Brust', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'FT 360 Brustpresse - Chestpress', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Bankdrücken', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Flys', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Schrägbankdrücken', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Bankdrücken', group: 'Brust', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Schrägbankdrücken', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Liegestütze', group: 'Brust', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Single Arm Cable Fly Low to High', group: 'Brust', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Cybex advanced lat pull down machine', group: 'Rücken', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Latzug', group: 'Rücken', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Rückenstrecker', group: 'Rücken', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Rudern sitzend', group: 'Rücken', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Deadlift High Pull', group: 'Rücken', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell High Pulls', group: 'Rücken', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Kreuzheben', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Rudern Vorgebeugt', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Klimmzugmaschine', group: 'Rücken', level: 'Anfänger', gear: 'both', unit: 'kg' },
  { name: 'Klimmzüge', group: 'Rücken', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'body' },
  { name: 'Kurzhantel Kreuzheben', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Rudern einarmig', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Shrug', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Überzüge', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Good Morning', group: 'Rücken', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Kreuzheben', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Rumänisches Kreuzheben', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Rudern Vorgebeugt', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Rudern aufrecht', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Rückenstrecker', group: 'Rücken', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Superman', group: 'Rücken', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'TRX Rudern', group: 'Rücken', level: 'Anfänger', gear: 'both', unit: 'kg' },
  { name: 'Banded Straight Arm Pull Down', group: 'Rücken', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Banded Pull Up', group: 'Rücken', level: 'Anfänger', gear: 'both', unit: 'body' },
  { name: 'Landmine Row', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Single Arm Landmine Row', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Rudern aufrecht', group: 'Rücken', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Reverse Fly', group: 'Schultern', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Schulterpresse', group: 'Schultern', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Halo', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Schwungdrücken', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Flies vorgebeugt', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Frontheben', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Schulterdrücken', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Schwungdrücken', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Seitheben', group: 'Schultern', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Landmine Press', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Schulterdrücken', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Schwungdrücken', group: 'Schultern', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Pike Push Ups', group: 'Schultern', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'body' },
  { name: 'Face Pulls', group: 'Schultern', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Single Arm Cable Lateral Raises', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Landmine Press 2', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Schulterdrücken mit Ball', group: 'Schultern', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Aufsteiger - Step Ups', group: 'Beine', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'body' },
  { name: 'Ausfallschritte - Lunges', group: 'Beine', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Box Sprünge - Box Jumps', group: 'Beine', level: 'Experte', gear: 'both', unit: 'body' },
  { name: 'Cybex Beinbeuger sitzend', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Beinbeuger einbeinig', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Beinpresse', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Beinstrecker', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex plate loaded squat press', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex plate loaded leg press', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex plate loaded Wadenheben sitzend', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Frontkniebeugen', group: 'Beine', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Goblet Squats', group: 'Beine', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Seitliche Ausfallschritte', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kniebeugen - Squat', group: 'Beine', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Kurzhantel Aufsteiger', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Ausfallschritte', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Bulgarische Ausfallschrittkniebeuge', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Frontkniebeugen', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Aufsteiger', group: 'Beine', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Ausfallschritte', group: 'Beine', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Frontkniebeugen', group: 'Beine', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Kniebeugen', group: 'Beine', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'TRX Ausfallschrittkniebeuge', group: 'Beine', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'TRX Kniebeuge', group: 'Beine', level: 'Anfänger', gear: 'both', unit: 'kg' },
  { name: 'Bauchrollen mit Ball', group: 'Bauch', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'Beinheben Hängend', group: 'Bauch', level: 'Experte', gear: 'bodyweight', unit: 'body' },
  { name: 'Sit Ups', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Crunches', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Cybex Bauchmaschine', group: 'Bauch', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Half Kneeling Banded Rotation', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'High to Low Wood Chop', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Russian Twists', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'L Sit', group: 'Bauch', level: 'Experte', gear: 'bodyweight', unit: 'time' },
  { name: 'Landmine Rotation', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Rollouts', group: 'Bauch', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Low to High Wood Chop', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Mountain Climber', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'time' },
  { name: 'Plank', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'time' },
  { name: 'Plank mit Ball', group: 'Bauch', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'Reverse Crunches', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Russian Twists', group: 'Bauch', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Seitliche Plank - Side Plank', group: 'Bauch', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'time' },
  { name: 'TRX Crunches', group: 'Bauch', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'TRX Plank', group: 'Bauch', level: 'Fortgeschritten', gear: 'both', unit: 'time' },
  { name: 'V Up', group: 'Bauch', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'kg' },
  { name: 'V Up mit Ball', group: 'Bauch', level: 'Experte', gear: 'both', unit: 'kg' },
  { name: 'Kettlebell Renegade Rows', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Renegade Row', group: 'Bauch', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Arnold Press', group: 'Arme', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Barbell Arm Curl', group: 'Arme', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Cable Bicep Curl', group: 'Arme', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cable Tricep Extension', group: 'Arme', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Hammercurls', group: 'Arme', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Konzentrations Curl', group: 'Arme', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Trizeps Kickbacks', group: 'Arme', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Bizepscurls', group: 'Arme', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Trizepsdips mit Ball', group: 'Arme', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'Zottman Curl', group: 'Arme', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Assault Bike', group: 'Cardio', level: 'Fortgeschritten', gear: 'both', unit: 'cardio' },
  { name: 'Assault Runner', group: 'Cardio', level: 'Anfänger', gear: 'both', unit: 'cardio' },
  { name: 'Bike Erg', group: 'Cardio', level: 'Anfänger', gear: 'both', unit: 'cardio' },
  { name: 'Jumping Jacks', group: 'Cardio', level: 'Anfänger', gear: 'bodyweight', unit: 'cardio' },
  { name: 'Maschine Rudern - Row Machine', group: 'Cardio', level: 'Anfänger', gear: 'both', unit: 'cardio' },
  { name: 'Ski Erg', group: 'Cardio', level: 'Anfänger', gear: 'both', unit: 'cardio' },
  { name: 'Stretching Lower Body', group: 'Stretching', level: 'Anfänger', gear: 'bodyweight', unit: 'time' },
  { name: 'Stretching Upper Body', group: 'Stretching', level: 'Anfänger', gear: 'bodyweight', unit: 'time' },
  { name: 'Kettlebell Turkish Get Ups', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Überkopf Kniebeuge', group: 'Ganzkörper', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Umsetzen und Drücken', group: 'Ganzkörper', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Windmills', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Standreissen', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kurzhantel Standumsetzen', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Standreissen', group: 'Ganzkörper', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Standumsetzen', group: 'Ganzkörper', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Überkopfkniebeuge', group: 'Ganzkörper', level: 'Experte', gear: 'machine', unit: 'kg' },
  { name: 'Push Ups mit Ball', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'both', unit: 'kg' },
  { name: 'Sled Push and Pull', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Push Ups', group: 'Ganzkörper', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'Sled Push / Pull', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Swings', group: 'Ganzkörper', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Wall Balls', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Burpee', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'bodyweight', unit: 'body' },
  { name: 'Battle Rope', group: 'Ganzkörper', level: 'Anfänger', gear: 'both', unit: 'cardio' },
  { name: 'FT 360 Lunge and Chest Fly', group: 'Ganzkörper', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Abduktoren', group: 'Hüfte', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Adduktoren', group: 'Hüfte', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Cybex Hüftstrecker', group: 'Hüfte', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Langhantel Hip Thrusts', group: 'Hüfte', level: 'Fortgeschritten', gear: 'machine', unit: 'kg' },
  { name: 'Lateral Band Walk', group: 'Hüfte', level: 'Anfänger', gear: 'both', unit: 'kg' },
  { name: 'Rückenbrücke - Glute Bridge', group: 'Hüfte', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'General Warm Up Bodyweight 1', group: 'Erwärmung', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'General Warm Up Bodyweight 2', group: 'Erwärmung', level: 'Anfänger', gear: 'bodyweight', unit: 'body' },
  { name: 'General Warm Up with Equipment', group: 'Erwärmung', level: 'Anfänger', gear: 'both', unit: 'kg' },
  { name: 'Kettlebell Farmer Carry', group: 'Loaded Carry', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Suitcase Carry', group: 'Loaded Carry', level: 'Anfänger', gear: 'machine', unit: 'kg' },
  { name: 'Kettlebell Reissen - Snatches', group: 'Lifting', level: 'Experte', gear: 'machine', unit: 'kg' },
];
