// charts.js — hand-rolled inline SVG charts. Original line/bar geometry generated by
// qwen2.5-coder:14b in three calls; reworked by Claude for v5 against the dataviz rules:
//
//   * one series per chart, so one colour — var(--accent) for every mark. The old code
//     passed a different hex per chart (green here, sky blue there, amber over there),
//     which encoded nothing: the heading already says what the chart is. Colour that
//     carries no information is just noise, and those hexes also failed the dark-surface
//     lightness band when checked with the palette validator.
//   * a solid hairline baseline and recessive gridlines — never dashed.
//   * selective direct labels: the latest value only, never a number on every point.
//   * a <title> in every mark, which is the whole hover layer. Native SVG tooltips need
//     no JavaScript and no library, which is the only kind of interactivity a PWA that
//     must work in a basement with no signal can honestly promise.
//   * 8px markers and a 2px gap between bars.

function r6(x) {
  return Math.round(x * 1e6) / 1e6;
}

export function esc(s) {
  s = String(s);
  s = s.replace(/&/g, '&amp;');
  s = s.replace(/</g, '&lt;');
  s = s.replace(/>/g, '&gt;');
  s = s.replace(/"/g, '&quot;');
  s = s.replace(/'/g, '&#39;');
  return s;
}

export function niceScale(min, max, targetTicks) {
  if (!isFinite(targetTicks) || targetTicks <= 0) {
    targetTicks = 4;
  }
  if (!isFinite(min) || !isFinite(max)) {
    min = 0;
    max = 1;
  }
  if (max <= min) {
    max = min + 1;
  }
  const range = max - min;
  const raw = range / targetTicks;
  const pow10 = Math.pow(10, Math.floor(Math.log10(raw)));
  const frac = raw / pow10;
  const mults = [1, 2, 2.5, 5, 10];
  let mult = mults.find(m => m >= frac) || 10;
  const step = r6(mult * pow10);
  const niceMin = r6(Math.floor(min / step) * step);
  const niceMax = r6(Math.ceil(max / step) * step);
  const count = Math.round((niceMax - niceMin) / step);
  const ticks = Array.from({ length: count + 1 }, (_, i) => r6(niceMin + i * step));
  ticks[count] = niceMax;
  return { min: niceMin, max: niceMax, step, ticks };
}

/** Axis numbers stay short so they never collide: 1250 -> "1.3k". */
export function fmtTick(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return '';
  const a = Math.abs(n);
  if (a >= 10000) return `${Math.round(n / 1000)}k`;
  if (a >= 1000) return `${r6(Math.round(n / 100) / 10)}k`;
  return String(r6(Math.round(n * 100) / 100));
}

/** "2031-03-09" -> "09.03.", "2031-W34" -> "W34". Anything else is passed through. */
export function fmtKeyShort(key) {
  const s = String(key == null ? '' : key);
  let m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (m) return `${m[3]}.${m[2]}.`;
  m = /^(\d{4})-W(\d{1,2})$/.exec(s);
  if (m) return `W${m[2]}`;
  return s;
}

/** First, middle and last only — enough to orient, never enough to collide. */
function tickIndices(n) {
  if (n <= 1) return [0];
  if (n <= 3) return Array.from({ length: n }, (_, i) => i);
  return [0, Math.floor((n - 1) / 2), n - 1];
}

function emptySvg(W, H, message) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${esc(message)}">`
    + `<text x="${W / 2}" y="${H / 2}" text-anchor="middle" class="empty">${esc(message)}</text></svg>`;
}

function frame(series, opts) {
  const o = opts || {};
  const W = o.width || 320;
  const H = o.height || 180;
  const L = 42, R = 14, T = 14, B = 30;
  return {
    o, W, H, L, R, T, B,
    innerW: W - L - R,
    innerH: H - T - B,
    label: o.label || '',
    empty: o.empty || 'No data yet',
    n: x => Math.round(x * 100) / 100,
  };
}

function axisAndGrid(f, sc, py) {
  let svg = '';
  for (const t of sc.ticks) {
    svg += `<line class="grid" x1="${f.L}" y1="${f.n(py(t))}" x2="${f.W - f.R}" y2="${f.n(py(t))}" />`
      + `<text class="ytick" x="${f.L - 6}" y="${f.n(py(t)) + 4}" text-anchor="end">${esc(fmtTick(t))}</text>`;
  }
  return svg;
}

function xLabels(f, series, px) {
  let svg = '';
  for (const i of tickIndices(series.length)) {
    const anchor = series.length <= 1 || i === 0 ? (series.length <= 1 ? 'middle' : 'start')
      : i === series.length - 1 ? 'end' : 'middle';
    const x = series.length <= 1 ? f.L + f.innerW / 2 : px(i);
    svg += `<text class="xtick" x="${f.n(x)}" y="${f.H - 9}" text-anchor="${anchor}">${esc(fmtKeyShort(series[i].key))}</text>`;
  }
  return svg;
}

function aria(f, series, values) {
  const lo = Math.min(...values);
  const hi = Math.max(...values);
  return esc(`${f.label ? f.label + '. ' : ''}${series.length} points, from ${fmtTick(lo)} to ${fmtTick(hi)}, latest ${fmtTick(values[values.length - 1])}.`);
}

export function lineChart(series, opts) {
  const f = frame(series, opts);
  if (!Array.isArray(series) || series.length === 0) return emptySvg(f.W, f.H, f.empty);

  const values = series.map(p => { const v = Number(p.value); return Number.isFinite(v) ? v : 0; });
  const sc = niceScale(Math.min(...values), Math.max(...values), 4);
  const span = (sc.max - sc.min) || 1;
  const px = i => series.length === 1 ? f.L + f.innerW / 2 : f.L + i * (f.innerW / (series.length - 1));
  const py = v => f.T + f.innerH * (1 - (v - sc.min) / span);
  const n = f.n;
  const dotR = series.length > 10 ? 3 : 4;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f.W} ${f.H}" width="100%" role="img" aria-label="${aria(f, series, values)}">`;
  svg += axisAndGrid(f, sc, py);
  svg += `<line class="axis" x1="${f.L}" y1="${n(py(sc.min))}" x2="${f.W - f.R}" y2="${n(py(sc.min))}" />`;
  svg += `<polyline class="line" fill="none" points="${values.map((v, i) => n(px(i)) + ',' + n(py(v))).join(' ')}" />`;

  for (let i = 0; i < series.length; i++) {
    svg += `<circle class="dot" cx="${n(px(i))}" cy="${n(py(values[i]))}" r="${dotR}">`
      + `<title>${esc(series[i].key)}: ${esc(fmtTick(values[i]))}</title></circle>`;
  }

  // One direct label, on the latest point, nudged inboard so it cannot fall off the edge.
  const li = series.length - 1;
  const lx = Math.min(f.W - f.R, Math.max(f.L, px(li)));
  const ly = Math.max(f.T + 9, py(values[li]) - 9);
  svg += `<text class="value" x="${n(lx)}" y="${n(ly)}" text-anchor="${series.length === 1 ? 'middle' : 'end'}">${esc(fmtTick(values[li]))}</text>`;

  svg += xLabels(f, series, px);
  svg += `</svg>`;
  return svg;
}

export function barChart(series, opts) {
  const f = frame(series, opts);
  if (!Array.isArray(series) || series.length === 0) return emptySvg(f.W, f.H, f.empty);

  const values = series.map(p => { const v = Number(p.value); return Number.isFinite(v) ? v : 0; });
  const sc = niceScale(Math.min(0, ...values), Math.max(...values), 4);
  const span = (sc.max - sc.min) || 1;
  const n = f.n;
  const py = v => f.T + f.innerH * (1 - (v - sc.min) / span);
  const slot = f.innerW / series.length;
  const bw = Math.max(2, Math.min(slot - 2, 30)); // a 2px surface gap between neighbours
  const bx = i => f.L + i * slot + (slot - bw) / 2;
  const base = py(Math.max(sc.min, 0));

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${f.W} ${f.H}" width="100%" role="img" aria-label="${aria(f, series, values)}">`;
  svg += axisAndGrid(f, sc, py);

  for (let i = 0; i < series.length; i++) {
    const top = Math.min(py(values[i]), base);
    const h = Math.max(1, Math.abs(base - py(values[i])));
    svg += `<rect class="bar" x="${n(bx(i))}" y="${n(top)}" width="${n(bw)}" height="${n(h)}" rx="4">`
      + `<title>${esc(series[i].key)}: ${esc(fmtTick(values[i]))}</title></rect>`;
  }

  svg += `<line class="axis" x1="${f.L}" y1="${n(base)}" x2="${f.W - f.R}" y2="${n(base)}" />`;

  const li = series.length - 1;
  svg += `<text class="value" x="${n(bx(li) + bw / 2)}" y="${n(Math.max(f.T + 9, py(values[li]) - 6))}" text-anchor="middle">${esc(fmtTick(values[li]))}</text>`;

  svg += xLabels(f, series, i => f.L + i * slot + slot / 2);
  svg += `</svg>`;
  return svg;
}
