// charts.js — hand-rolled inline SVG charts. Generated by qwen2.5-coder:14b (3 parts), integrated by Claude.

function r6(x) {
  return Math.round(x * 1e6) / 1e6;
}

export function esc(s) {
  s = String(s);
  s = s.replace(/&/g, '&amp;');
  s = s.replace(/</g, '&lt;');
  s = s.replace(/>/g, '&gt;');
  s = s.replace(/"/g, '&quot;');
  s = s.replace(/'/g, '&#39;');
  return s;
}

export function niceScale(min, max, targetTicks) {
  if (!isFinite(targetTicks) || targetTicks <= 0) {
    targetTicks = 4;
  }
  if (!isFinite(min) || !isFinite(max)) {
    min = 0;
    max = 1;
  }
  if (max <= min) {
    max = min + 1;
  }
  const range = max - min;
  const raw = range / targetTicks;
  const pow10 = Math.pow(10, Math.floor(Math.log10(raw)));
  const frac = raw / pow10;
  const mults = [1, 2, 2.5, 5, 10];
  let mult = mults.find(m => m >= frac) || 10;
  const step = r6(mult * pow10);
  const niceMin = r6(Math.floor(min / step) * step);
  const niceMax = r6(Math.ceil(max / step) * step);
  const count = Math.round((niceMax - niceMin) / step);
  const ticks = Array.from({ length: count + 1 }, (_, i) => r6(niceMin + i * step));
  ticks[count] = niceMax;
  return { min: niceMin, max: niceMax, step, ticks };
}

export function lineChart(series, opts) {
  const o = opts || {};
  const W = o.width || 320, H = o.height || 180, C = o.color || '#4f7cff';
  const L = 40, R = 12, T = 12, B = 26;
  const innerW = W - L - R, innerH = H - T - B;
  if (!Array.isArray(series) || series.length === 0)
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" role="img"><text x="${W/2}" y="${H/2}" text-anchor="middle" class="empty">No data yet</text></svg>`;
  const values = series.map(p => { const v = Number(p.value); return Number.isFinite(v) ? v : 0; });
  const sc = niceScale(Math.min(...values), Math.max(...values), 4);
  const span = (sc.max - sc.min) || 1;
  const px = i => series.length === 1 ? L + innerW/2 : L + i * (innerW/(series.length-1));
  const py = v => T + innerH * (1 - (v - sc.min)/span);
  const n = x => Math.round(x*100)/100;
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" role="img">`;
  for (let t of sc.ticks) {
    svg += `<line class="grid" x1="${L}" y1="${n(py(t))}" x2="${W-R}" y2="${n(py(t))}" /><text class="ytick" x="${L-6}" y="${n(py(t))+4}" text-anchor="end">${esc(t)}</text>`;
  }
  svg += `<polyline class="line" fill="none" stroke="${C}" points="${values.map((v,i)=>n(px(i))+','+n(py(v))).join(' ')}" />`;
  for (let i = 0; i < series.length; i++) {
    svg += `<circle class="dot" cx="${n(px(i))}" cy="${n(py(values[i]))}" r="3" fill="${C}" />`;
  }
  if (series.length === 1) {
    svg += `<text class="xtick" x="${n(L+innerW/2)}" y="${H-8}" text-anchor="middle">${esc(series[0].key)}</text>`;
  } else {
    svg += `<text class="xtick" x="${L}" y="${H-8}" text-anchor="start">${esc(series[0].key)}</text><text class="xtick" x="${W-R}" y="${H-8}" text-anchor="end">${esc(series[series.length-1].key)}</text>`;
  }
  svg += `</svg>`;
  return svg;
}

export function barChart(series, opts) {
  const o = opts || {};
  const W = o.width || 320, H = o.height || 180, C = o.color || '#4f7cff';
  const L = 40, R = 12, T = 12, B = 26;
  const innerW = W - L - R, innerH = H - T - B;
  if (!Array.isArray(series) || series.length === 0)
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" role="img"><text x="${W/2}" y="${H/2}" text-anchor="middle" class="empty">No data yet</text></svg>`;
  const values = series.map(p => { const v = Number(p.value); return Number.isFinite(v) ? v : 0; });
  const sc = niceScale(Math.min(0, ...values), Math.max(...values), 4);
  const span = (sc.max - sc.min) || 1;
  const n = x => Math.round(x*100)/100;
  const py = v => T + innerH * (1 - (v - sc.min)/span);
  const slot = innerW / series.length;
  const bw = Math.max(2, slot * 0.7);
  const bx = i => L + i*slot + (slot - bw)/2;
  const base = py(Math.max(sc.min, 0));

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="100%" role="img">`;
  for (let t of sc.ticks) {
    svg += `<line class="grid" x1="${L}" y1="${n(py(t))}" x2="${W-R}" y2="${n(py(t))}" /><text class="ytick" x="${L-6}" y="${n(py(t))+4}" text-anchor="end">${esc(t)}</text>`;
  }
  for (let i = 0; i < series.length; i++) {
    let top = Math.min(py(values[i]), base), h = Math.max(1, Math.abs(base - py(values[i])));
    svg += `<rect class="bar" x="${n(bx(i))}" y="${n(top)}" width="${n(bw)}" height="${n(h)}" rx="2" fill="${C}" />`;
  }
  if (series.length === 1) {
    svg += `<text class="xtick" x="${n(L+innerW/2)}" y="${H-8}" text-anchor="middle">${esc(series[0].key)}</text>`;
  } else {
    svg += `<text class="xtick" x="${L}" y="${H-8}" text-anchor="start">${esc(series[0].key)}</text><text class="xtick" x="${W-R}" y="${H-8}" text-anchor="end">${esc(series[series.length-1].key)}</text>`;
  }
  svg += `</svg>`;
  return svg;
}
