// coach.js — deterministic progression rules. No model runs here and none ever will:
// double progression, stall detection and deloads are arithmetic, and arithmetic is
// instant, offline, free, and cannot hallucinate a weight. Generated by
// qwen2.5-coder:14b in two calls; three bugs found and fixed by Claude (unknown unit
// spread `undefined` instead of falling back to kg, an all-invalid `at` returned
// Infinity, and the deload threshold was one session too eager).
//
// Pure functions only: no DOM, no IndexedDB, no imports.

const DEFAULTS = {
  kg:    { repMin: 8,  repMax: 12, increment: 2.5, step: 0.5 },
  stufe: { repMin: 10, repMax: 15, increment: 1,   step: 0.5 },
  time:  { repMin: 0,  repMax: 0,  increment: 5,   step: 5   },
};

// A run of this many sessions at one load with no rep gain earns a deload. Four
// sessions is three consecutive failures to progress — at one session every 3-4 days
// that is a fortnight of standing still, which is a real stall rather than a bad day.
const STALL_SESSIONS = 4;

export function roundToStep(value, step) {
  const v = Number(value);
  if (!Number.isFinite(v)) return 0;
  const s = Number(step);
  if (!Number.isFinite(s) || s <= 0) return parseFloat(v.toFixed(6));
  return parseFloat((Math.round(v / s) * s).toFixed(6));
}

export function targetsFor(exercise) {
  const unit = (exercise && exercise.unit) || 'kg';
  const target = { ...(DEFAULTS[unit] || DEFAULTS.kg) };
  for (const key of ['repMin', 'repMax', 'increment']) {
    if (exercise && typeof exercise === 'object') {
      const v = Number(exercise[key]);
      if (Number.isFinite(v) && v > 0) target[key] = v;
    }
  }
  return target;
}

export function sessionSummaries(sets) {
  if (!Array.isArray(sets)) return [];

  const grouped = new Map();
  for (const entry of sets) {
    if (!entry || typeof entry !== 'object' || entry.done !== true) continue;
    const w = Number(entry.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = entry.sessionId;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(entry);
  }

  const summaries = [];
  for (const [sessionId, group] of grouped) {
    const load = Math.max(...group.map(e => Number(e.weight)));
    const atWork = group.filter(e => Number(e.weight) === load);
    const reps = atWork
      .map(e => Number(e.reps))
      .filter(r => Number.isFinite(r) && r > 0);
    const times = group.map(e => Number(e.at)).filter(Number.isFinite);
    const at = times.length ? Math.min(...times) : 0;
    summaries.push({ sessionId, at, load, reps, setCount: atWork.length });
  }

  return summaries.sort((a, b) =>
    a.at !== b.at ? a.at - b.at : String(a.sessionId).localeCompare(String(b.sessionId)));
}

export function suggest(sets, exercise) {
  const t = targetsFor(exercise);
  const rawUnit = exercise && exercise.unit;
  const unit = rawUnit === 'stufe' ? 'stufe' : rawUnit === 'time' ? 'time' : 'kg';

  const list = Array.isArray(sets) ? sets : [];
  const wanted = exercise && typeof exercise === 'object' && exercise.id ? exercise.id : null;
  const filtered = wanted ? list.filter(s => s && s.exerciseId === wanted) : list;
  const hist = sessionSummaries(filtered);

  if (hist.length === 0) {
    return {
      kind: 'first-time', load: null, reps: null,
      reason: 'No logged sets yet — do one session and the coach starts from there.',
      lastLoad: null, lastReps: [], sessionsAtLoad: 0,
    };
  }

  const last = hist[hist.length - 1];
  const lastLoad = last.load;
  const lastReps = last.reps;

  let sessionsAtLoad = 0;
  for (let i = hist.length - 1; i >= 0; i--) {
    if (Math.abs(hist[i].load - lastLoad) <= 0.001) sessionsAtLoad++;
    else break;
  }
  if (sessionsAtLoad === 0) sessionsAtLoad = 1;

  const base = { lastLoad, lastReps, sessionsAtLoad };

  if (unit === 'time') {
    const best = hist.reduce((m, h) => Math.max(m, h.load), 0);
    if (lastLoad >= best - 0.001) {
      return {
        kind: 'add-load', load: roundToStep(lastLoad + t.increment, t.step), reps: null,
        reason: `You matched your best hold — go ${t.increment} seconds longer.`, ...base,
      };
    }
    return {
      kind: 'hold', load: best, reps: null,
      reason: `Your best hold is ${best} seconds — match that again.`, ...base,
    };
  }

  if (lastReps.length === 0) {
    return {
      kind: 'no-reps', load: lastLoad, reps: null,
      reason: 'This was logged without rep counts, so there is nothing to progress from. Add reps next time.',
      ...base,
    };
  }

  const weakest = Math.min(...lastReps);

  if (weakest >= t.repMax) {
    return {
      kind: 'add-load', load: roundToStep(lastLoad + t.increment, t.step), reps: t.repMin,
      reason: `Every set hit ${t.repMax} reps — add load and drop back to ${t.repMin}.`, ...base,
    };
  }

  if (sessionsAtLoad >= STALL_SESSIONS) {
    const run = hist.slice(hist.length - sessionsAtLoad);
    const sumReps = h => h.reps.reduce((a, b) => a + b, 0);
    const improving = sumReps(run[run.length - 1]) > sumReps(run[0]);
    if (!improving) {
      const deloaded = unit === 'stufe'
        ? Math.max(1, lastLoad - t.increment)
        : Math.max(t.step, roundToStep(lastLoad * 0.9, t.step));
      return {
        kind: 'deload', load: deloaded, reps: t.repMin,
        reason: `Stuck at the same load for ${sessionsAtLoad} sessions with no rep gain. Drop the load, rebuild, come back stronger.`,
        ...base,
      };
    }
  }

  const target = Math.min(t.repMax, weakest + 1);
  return {
    kind: 'add-reps', load: lastLoad, reps: target,
    reason: `Your weakest set was ${weakest} reps. Same load, aim for ${target} on every set.`,
    ...base,
  };
}
