// coach.js — deterministic progression rules. No model runs here and none ever will:
// double progression, stall detection and deloads are arithmetic, and arithmetic is
// instant, offline, free, and cannot hallucinate a weight. Generated by
// qwen2.5-coder:14b in two calls; three bugs found and fixed by Claude (unknown unit
// spread `undefined` instead of falling back to kg, an all-invalid `at` returned
// Infinity, and the deload threshold was one session too eager).
//
// Pure functions only: no DOM and no IndexedDB. The one import is history.js, which is
// pure as well and owns the definition of "the previous session, sets in order".
import { sessionsFor, loadRange, isOutlier } from './history.js';

const DEFAULTS = {
  kg:     { repMin: 8,  repMax: 12, increment: 2.5, step: 0.5 },
  stufe:  { repMin: 10, repMax: 15, increment: 1,   step: 0.5 },
  time:   { repMin: 0,  repMax: 0,  increment: 5,   step: 5   },
  // Bodyweight ranges run wider: with no load to add, reps are the only lever, so the
  // top of the range is where you add a set or pick a harder variation instead.
  body:   { repMin: 8,  repMax: 20, increment: 1,   step: 1   },
  cardio: { repMin: 0,  repMax: 0,  increment: 2,   step: 1   },
};

// A run of this many sessions at one load with no rep gain earns a deload. Four
// sessions is three consecutive failures to progress — at one session every 3-4 days
// that is a fortnight of standing still, which is a real stall rather than a bad day.
const STALL_SESSIONS = 4;

export function roundToStep(value, step) {
  const v = Number(value);
  if (!Number.isFinite(v)) return 0;
  const s = Number(step);
  if (!Number.isFinite(s) || s <= 0) return parseFloat(v.toFixed(6));
  return parseFloat((Math.round(v / s) * s).toFixed(6));
}

export function targetsFor(exercise) {
  const unit = (exercise && exercise.unit) || 'kg';
  const target = { ...(DEFAULTS[unit] || DEFAULTS.kg) };
  for (const key of ['repMin', 'repMax', 'increment']) {
    if (exercise && typeof exercise === 'object') {
      const v = Number(exercise[key]);
      if (Number.isFinite(v) && v > 0) target[key] = v;
    }
  }
  return target;
}

/** Like sessionSummaries, but for exercises that carry no load at all: bodyweight work,
 *  where the rep count IS the record. Grouping by heaviest set is meaningless there, so
 *  every completed rep count in the session is kept. */
export function repSummaries(sets) {
  if (!Array.isArray(sets)) return [];

  // A session that was ticked off but never had its reps filled in still HAPPENED, so it
  // is kept with an empty reps array — exactly as a loaded exercise keeps a session that
  // recorded a weight but no reps. Dropping it would make the coach claim you had never
  // trained the movement at all.
  const grouped = new Map();
  for (const entry of sets) {
    if (!entry || typeof entry !== 'object' || entry.done !== true) continue;
    const key = entry.sessionId;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(entry);
  }

  const out = [];
  for (const [sessionId, group] of grouped) {
    const times = group.map(e => Number(e.at)).filter(Number.isFinite);
    const reps = group.map(e => Number(e.reps)).filter(r => Number.isFinite(r) && r > 0);
    out.push({
      sessionId,
      at: times.length ? Math.min(...times) : 0,
      load: null,
      reps,
      setCount: group.length,
    });
  }
  return out.sort((a, b) =>
    a.at !== b.at ? a.at - b.at : String(a.sessionId).localeCompare(String(b.sessionId)));
}

export function sessionSummaries(sets) {
  if (!Array.isArray(sets)) return [];

  const grouped = new Map();
  for (const entry of sets) {
    if (!entry || typeof entry !== 'object' || entry.done !== true) continue;
    const w = Number(entry.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = entry.sessionId;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(entry);
  }

  const summaries = [];
  for (const [sessionId, group] of grouped) {
    const load = Math.max(...group.map(e => Number(e.weight)));
    const atWork = group.filter(e => Number(e.weight) === load);
    const reps = atWork
      .map(e => Number(e.reps))
      .filter(r => Number.isFinite(r) && r > 0);
    const times = group.map(e => Number(e.at)).filter(Number.isFinite);
    const at = times.length ? Math.min(...times) : 0;
    summaries.push({ sessionId, at, load, reps, setCount: atWork.length });
  }

  return summaries.sort((a, b) =>
    a.at !== b.at ? a.at - b.at : String(a.sessionId).localeCompare(String(b.sessionId)));
}

/** One target per set position, taken from what you did in that same position last time.
 *  This is the branch that matters when the load changes from set to set: measuring a
 *  pyramid against its own heaviest set throws away four fifths of the session, and one
 *  mistyped number then becomes the only thing the coach can see.
 *
 *  `sessions` is oldest-first, from history.sessionsFor. */
function perSetTargets(sessions, t, unit) {
  if (!sessions.length) return [];
  const last = sessions[sessions.length - 1].rows;
  const out = [];

  for (let i = 0; i < last.length; i++) {
    const load = Number(last[i].weight);
    const reps = Number(last[i].reps);
    const hasLoad = Number.isFinite(load) && load > 0;
    const hasReps = Number.isFinite(reps) && reps > 0;
    if (!hasLoad && unit !== 'body') continue;

    const lastLoad = hasLoad ? load : null;
    const mk = (kind, l, r, reason) =>
      ({ index: i, kind, load: l, reps: r, lastLoad, lastReps: hasReps ? reps : null, reason });

    if (!hasReps) {
      out.push(mk('no-reps', lastLoad, null, 'logged without reps'));
      continue;
    }

    // How many sessions in a row put the same load in this very position, and did the reps
    // there move at all? Position by position, so a stuck top set is spotted even while the
    // warm-up sets underneath it climb.
    let run = 0;
    for (let k = sessions.length - 1; k >= 0; k--) {
      const row = sessions[k].rows[i];
      if (!row) break;
      const l = Number(row.weight);
      if (!Number.isFinite(l) || (hasLoad && Math.abs(l - load) > 0.001)) break;
      run++;
    }
    if (unit !== 'body' && run >= STALL_SESSIONS) {
      const first = Number(sessions[sessions.length - run].rows[i].reps);
      if (!(Number.isFinite(first) && reps > first)) {
        const deloaded = unit === 'stufe'
          ? Math.max(1, load - t.increment)
          : Math.max(t.step, roundToStep(load * 0.9, t.step));
        out.push(mk('deload', deloaded, t.repMin, `stuck ${run} sessions`));
        continue;
      }
    }

    if (reps >= t.repMax) {
      const up = unit === 'body' ? null : roundToStep(load + t.increment, t.step);
      out.push(mk('add-load', unit === 'body' ? null : up, unit === 'body' ? t.repMax : t.repMin,
        unit === 'body' ? 'top of the range' : 'hit the top'));
      continue;
    }
    out.push(mk('add-reps', lastLoad, Math.min(t.repMax, reps + 1), '+1 rep'));
  }
  return out;
}

/** True when the last session did NOT run straight sets — the case the old single-figure
 *  advice was never right for. */
function loadsVary(sessions) {
  if (!sessions.length) return false;
  const loads = sessions[sessions.length - 1].rows
    .map(r => Number(r.weight))
    .filter(v => Number.isFinite(v) && v > 0);
  if (loads.length < 2) return false;
  return Math.max(...loads) - Math.min(...loads) > 0.001;
}

/** The straight-sets advice: one figure for the whole exercise, read off the heaviest set.
 *  Still exactly right when every set carries the same load — which is most exercises for
 *  most people — so it is left alone and wrapped rather than replaced. */
function coreSuggest(sets, exercise) {
  const t = targetsFor(exercise);
  const rawUnit = exercise && exercise.unit;
  const unit = ['stufe', 'time', 'body', 'cardio'].includes(rawUnit) ? rawUnit : 'kg';

  const list = Array.isArray(sets) ? sets : [];
  const wanted = exercise && typeof exercise === 'object' && exercise.id ? exercise.id : null;
  const byExercise = wanted ? list.filter(s => s && s.exerciseId === wanted) : list;

  // A number that is nowhere near anything you have ever lifted is a typo, not a personal
  // best. Left in, it becomes the heaviest set, and every suggestion from then on is built
  // on it — which is exactly how the coach came to ask for 479.5 kg on the Pulldown.
  const range = loadRange(byExercise, wanted, null);
  const filtered = range ? byExercise.filter(s => !isOutlier(s && s.weight, range)) : byExercise;

  const firstTime = () => ({
    kind: 'first-time', load: null, reps: null,
    reason: 'No logged sets yet — do one session and the coach starts from there.',
    lastLoad: null, lastReps: [], sessionsAtLoad: 0, perSet: [], varied: false,
  });

  // --- bodyweight: no load exists, so reps are the whole record ---
  if (unit === 'body') {
    const bh = repSummaries(filtered);
    if (bh.length === 0) return firstTime();
    const bLast = bh[bh.length - 1];
    const bReps = bLast.reps;
    const bBase = { lastLoad: null, lastReps: bReps, sessionsAtLoad: bh.length };
    if (bReps.length === 0) {
      return {
        kind: 'no-reps', load: null, reps: null,
        reason: 'This was logged without rep counts, so there is nothing to progress from. Add reps next time.',
        ...bBase,
      };
    }
    const bWeakest = Math.min(...bReps);
    if (bWeakest >= t.repMax) {
      return {
        kind: 'add-set', load: null, reps: t.repMax,
        reason: `Every set reached ${t.repMax} reps. There is no weight to add here — add another set, or move to a harder variation.`,
        ...bBase,
      };
    }
    const bTarget = Math.min(t.repMax, bWeakest + 1);
    return {
      kind: 'add-reps', load: null, reps: bTarget,
      reason: `Your weakest set was ${bWeakest} reps. Aim for ${bTarget} on every set.`,
      ...bBase,
    };
  }

  const hist = sessionSummaries(filtered);
  if (hist.length === 0) return firstTime();

  const last = hist[hist.length - 1];
  const lastLoad = last.load;
  const lastReps = last.reps;

  let sessionsAtLoad = 0;
  for (let i = hist.length - 1; i >= 0; i--) {
    if (Math.abs(hist[i].load - lastLoad) <= 0.001) sessionsAtLoad++;
    else break;
  }
  if (sessionsAtLoad === 0) sessionsAtLoad = 1;

  const base = { lastLoad, lastReps, sessionsAtLoad };

  // --- durations: a held plank in seconds, or a cardio piece in minutes ---
  if (unit === 'time' || unit === 'cardio') {
    const noun = unit === 'cardio' ? 'minutes' : 'seconds';
    const what = unit === 'cardio' ? 'effort' : 'hold';
    const best = hist.reduce((m, h) => Math.max(m, h.load), 0);
    if (lastLoad >= best - 0.001) {
      return {
        kind: 'add-load', load: roundToStep(lastLoad + t.increment, t.step), reps: null,
        reason: `You matched your best ${what} — go ${t.increment} ${noun} longer.`, ...base,
      };
    }
    return {
      kind: 'hold', load: best, reps: null,
      reason: `Your best ${what} is ${best} ${noun} — match that again.`, ...base,
    };
  }

  if (lastReps.length === 0) {
    return {
      kind: 'no-reps', load: lastLoad, reps: null,
      reason: 'This was logged without rep counts, so there is nothing to progress from. Add reps next time.',
      ...base,
    };
  }

  const weakest = Math.min(...lastReps);

  if (weakest >= t.repMax) {
    return {
      kind: 'add-load', load: roundToStep(lastLoad + t.increment, t.step), reps: t.repMin,
      reason: `Every set hit ${t.repMax} reps — add load and drop back to ${t.repMin}.`, ...base,
    };
  }

  if (sessionsAtLoad >= STALL_SESSIONS) {
    const run = hist.slice(hist.length - sessionsAtLoad);
    const sumReps = h => h.reps.reduce((a, b) => a + b, 0);
    const improving = sumReps(run[run.length - 1]) > sumReps(run[0]);
    if (!improving) {
      const deloaded = unit === 'stufe'
        ? Math.max(1, lastLoad - t.increment)
        : Math.max(t.step, roundToStep(lastLoad * 0.9, t.step));
      return {
        kind: 'deload', load: deloaded, reps: t.repMin,
        reason: `Stuck at the same load for ${sessionsAtLoad} sessions with no rep gain. Drop the load, rebuild, come back stronger.`,
        ...base,
      };
    }
  }

  const target = Math.min(t.repMax, weakest + 1);
  return {
    kind: 'add-reps', load: lastLoad, reps: target,
    reason: `Your weakest set was ${weakest} reps. Same load, aim for ${target} on every set.`,
    ...base,
  };
}

/**
 * What to aim for next. Always carries `perSet` — one target per set position, so the
 * screen can put a figure under every row — and `varied`, which says whether the last
 * session actually used different loads. When it did, `kind` becomes 'per-set' and the
 * single headline figure is dropped, because there isn't an honest one to give.
 */
export function suggest(sets, exercise) {
  const out = coreSuggest(sets, exercise);

  const rawUnit = exercise && exercise.unit;
  const unit = ['stufe', 'time', 'body', 'cardio'].includes(rawUnit) ? rawUnit : 'kg';
  // A duration is one effort per set with nothing to pyramid, so per-set targets would just
  // repeat the headline. Leave those exercises exactly as they were.
  if (unit === 'time' || unit === 'cardio') return { ...out, perSet: [], varied: false };

  const t = targetsFor(exercise);
  const list = Array.isArray(sets) ? sets : [];
  const wanted = exercise && typeof exercise === 'object' && exercise.id ? exercise.id : null;
  const byExercise = wanted ? list.filter(s => s && s.exerciseId === wanted) : list;
  const range = loadRange(byExercise, wanted, null);
  const clean = range ? byExercise.filter(s => !isOutlier(s && s.weight, range)) : byExercise;

  const sessions = sessionsFor(clean, wanted);
  const perSet = perSetTargets(sessions, t, unit);
  const varied = unit !== 'body' && loadsVary(sessions);

  if (!varied || perSet.length < 2 || out.kind === 'first-time' || out.kind === 'no-reps') {
    return { ...out, perSet, varied };
  }
  return {
    ...out, perSet, varied,
    kind: 'per-set', load: null, reps: null,
    reason: 'The load changed from set to set last time, so each set gets its own target — '
      + 'measured against the same set number, not against your heaviest.',
  };
}
