// csv.js — the export that gets your training out of this browser and into a spreadsheet.
// Semicolon-delimited by default: German Excel splits on ';' and would otherwise drop a
// whole workout into one cell. Generated by qwen2.5-coder:14b; its final sort compared
// a `stamp` property that the returned rows never carry (NaN comparator, silently no
// sorting at all), so Claude replaced it with a sort over a parallel timestamp list.
import { unitOf, toKg } from './units.js';

export const CSV_COLUMNS = ['date', 'time', 'routine', 'exercise', 'unit', 'set', 'load', 'load_kg', 'reps', 'volume_kg', 'done', 'notes'];

export function escapeCell(value, delimiter) {
  if (value === null || value === undefined) return '';
  const s = String(value);
  const d = delimiter || ';';
  if (s.includes(d) || s.includes('"') || s.includes('\n') || s.includes('\r')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

export function toCsv(rows, delimiter) {
  const d = delimiter || ';';
  const header = CSV_COLUMNS.join(d);
  if (!Array.isArray(rows) || rows.length === 0) return header;
  const lines = rows.map(row => CSV_COLUMNS.map(column => escapeCell(row && row[column], d)).join(d));
  return [header, ...lines].join('\r\n');
}

export function buildRows(data) {
  const d = data && typeof data === 'object' ? data : {};
  const exercises = Array.isArray(d.exercises) ? d.exercises : [];
  const sessions = Array.isArray(d.sessions) ? d.sessions : [];
  const sets = Array.isArray(d.sets) ? d.sets : [];

  const exerciseById = new Map(exercises.filter(Boolean).map(ex => [ex.id, ex]));
  const sessionById = new Map(sessions.filter(Boolean).map(s => [s.id, s]));

  const wrapped = sets
    .filter(s => s !== null && typeof s === 'object')
    .map(s => {
      const ex = exerciseById.get(s.exerciseId) || null;
      const session = sessionById.get(s.sessionId) || null;
      const at = Number(s.at);
      const stamp = Number.isFinite(at) && at > 0
        ? at
        : (session && Number(session.startedAt)) || 0;
      const dt = new Date(stamp);
      const load_kg = toKg(s.weight, ex);
      const repsNum = Number(s.reps);
      const reps = unitOf(ex).hasReps && Number.isFinite(repsNum) && repsNum > 0 ? repsNum : '';

      return {
        stamp,
        row: {
          date: `${dt.getFullYear()}-${String(dt.getMonth() + 1).padStart(2, '0')}-${String(dt.getDate()).padStart(2, '0')}`,
          time: `${String(dt.getHours()).padStart(2, '0')}:${String(dt.getMinutes()).padStart(2, '0')}`,
          routine: session && session.routineName ? session.routineName : '',
          exercise: ex && ex.name ? ex.name : 'Deleted exercise',
          unit: ex && ex.unit ? ex.unit : 'kg',
          set: Number.isFinite(Number(s.setIndex)) ? Number(s.setIndex) + 1 : 1,
          load: Number.isFinite(Number(s.weight)) ? Number(s.weight) : 0,
          load_kg,
          reps,
          volume_kg: reps === '' ? 0 : Math.round(load_kg * reps * 100) / 100,
          done: s.done === true ? 'yes' : 'no',
          notes: s.notes ? s.notes : '',
        },
      };
    });

  wrapped.sort((a, b) => a.stamp - b.stamp);
  return wrapped.map(w => w.row);
}
