// edits.js — two small things that guard against a slip of the thumb: moving an entry of a
// list without disturbing the list you were given, and writing the sentence that a delete
// dialog asks. Both are pure, so both are testable without a browser.
//
// Generated by Qwen3.6-35B-A3B (llama-server, --n-cpu-moe 20) from a written spec, 985 tokens
// at 55.7 tok/s. Claude's fixes: the no-index branch produced "Remove set this set?" because
// it concatenated the fallback into a sentence that already contained the noun; the count
// helper returned 2.7 unchanged for a fractional input; and an absent name used to leave
// `Delete the workout "this"` — the name is simply left out now.
//
// Pure functions only: no DOM, no IndexedDB, no imports.

export function moveItem(list, index, delta) {
  if (!Array.isArray(list)) {
    return [];
  }
  const out = list.slice();
  const i = Number(index);
  if (!Number.isInteger(i) || i < 0 || i >= out.length) {
    return out;
  }
  const d = Number(delta);
  if (!Number.isInteger(d)) {
    return out;
  }
  const target = i + d;
  if (target < 0 || target >= out.length) {
    return out;
  }
  const item = out.splice(i, 1)[0];
  out.splice(target, 0, item);
  return out;
}

/**
 * The text for a confirmation dialog, or null when there is nothing worth interrupting for.
 * Every message says what is about to be lost, because "Are you sure?" on its own tells you
 * nothing you did not already know.
 */
export function deleteWarning(kind, info) {
  const src = (typeof info === 'object' && info !== null) ? info : {};

  const count = function (field) {
    const val = Number(src[field]);
    if (Number.isFinite(val) && val >= 0) {
      return Math.floor(val);
    }
    return 0;
  };

  // A named thing is quoted; an unnamed one is simply not mentioned, rather than being
  // called "this" inside a sentence that already says which kind of thing it is.
  const named = typeof src.name === 'string' && src.name.trim().length > 0
    ? ' "' + src.name.trim() + '"'
    : '';

  const n = count('sets');

  if (kind === 'session') {
    let dateStr = '';
    if (typeof src.date === 'string' && src.date.trim().length > 0) {
      dateStr = ' from ' + src.date.trim();
    }
    let body;
    if (n === 0) {
      body = 'It has no logged sets. This cannot be undone.';
    } else if (n === 1) {
      body = '1 logged set will be deleted with it. This cannot be undone.';
    } else {
      body = n + ' logged sets will be deleted with it. This cannot be undone.';
    }
    return 'Delete the workout' + named + dateStr + '?\n\n' + body;
  }

  if (kind === 'routine') {
    const ex = count('exercises');
    let body;
    if (ex === 0) {
      body = 'It has no exercises. Your logged workouts are not affected.';
    } else if (ex === 1) {
      body = 'It lists 1 exercise. Your logged workouts are not affected.';
    } else {
      body = 'It lists ' + ex + ' exercises. Your logged workouts are not affected.';
    }
    return 'Delete the routine' + named + '?\n\n' + body;
  }

  if (kind === 'exercise') {
    let body;
    if (n === 0) {
      body = 'Nothing has been logged for it yet.';
    } else if (n === 1) {
      body = '1 logged set stays in your history but will show as "Removed exercise".';
    } else {
      body = n + ' logged sets stay in your history but will show as "Removed exercise".';
    }
    return 'Delete the exercise' + named + '?\n\n' + body;
  }

  if (kind === 'set') {
    // An untouched row holds nothing, and asking about it during a workout would be nagging.
    const weight = Number(src.weight);
    const reps = Number(src.reps);
    const empty = src.done !== true
      && !(Number.isFinite(weight) && weight > 0)
      && !(Number.isFinite(reps) && reps > 0);
    if (empty) {
      return null;
    }
    const idx = Number(src.index);
    if (Number.isFinite(idx)) {
      return 'Remove set ' + (Math.floor(idx) + 1) + '?';
    }
    return 'Remove this set?';
  }

  return 'Delete this?';
}
