// history.js — the same exercise, session by session, with the sets kept in the order they
// were actually performed. Everything that wants to say "and last time you did..." reads
// from here, so there is exactly one definition of what "last time" means.
//
// Why this module exists at all: state.sets arrives from IndexedDB in key order, and set ids
// are random strings, so the array order is arbitrary. Picking `list[list.length - 1]` as
// "the most recent set" — which the session screen used to do for its placeholders — really
// picks a random one. Order has to be reconstructed from `at`.
//
// Pure functions only: no DOM, no IndexedDB, no imports.
// Generated by qwen2.5-coder:14b from a written spec; isOutlier hardened by Claude to accept
// a numeric string, because values coming back out of an <input> are strings.

/** Every session this exercise appears in, oldest first, each with its sets in performed
 *  order. Only completed sets count — an unticked row is a plan, not a record. */
export function sessionsFor(sets, exerciseId) {
  if (!Array.isArray(sets)) return [];

  const filteredSets = sets.filter(s =>
    typeof s === 'object' && s !== null &&
    s.done === true &&
    (typeof exerciseId !== 'string' || exerciseId === '' || s.exerciseId === exerciseId)
  );

  const grouped = filteredSets.reduce((acc, s) => {
    if (!acc[s.sessionId]) {
      acc[s.sessionId] = [];
    }
    acc[s.sessionId].push(s);
    return acc;
  }, {});

  // Rows are ordered exactly the way the workout screen numbers them — by creation, not by
  // `at`, which is rewritten every time a set is ticked off. Otherwise "set 3 last time"
  // would mean the third set you happened to finish rather than the third row on screen.
  const ord = (x) => {
    const c = Number(x.createdAt);
    if (isFinite(c)) return c;
    const a = Number(x.at);
    return isFinite(a) ? a : 0;
  };

  const result = Object.entries(grouped).map(([sessionId, rows]) => {
    rows.sort((a, b) => {
      if (ord(a) !== ord(b)) return ord(a) - ord(b);
      const ia = Number(a.setIndex) || 0;
      const ib = Number(b.setIndex) || 0;
      if (ia !== ib) return ia - ib;
      return String(a.id).localeCompare(String(b.id));
    });

    const smallestAt = rows.reduce((min, s) => {
      const at = Number(s.at);
      return !isNaN(at) && at < min ? at : min;
    }, Infinity);

    return { sessionId, at: isFinite(smallestAt) ? smallestAt : 0, rows };
  });

  result.sort((a, b) => {
    if (a.at !== b.at) return a.at - b.at;
    return String(a.sessionId).localeCompare(String(b.sessionId));
  });

  return result;
}

/** The sets of the most recent session BEFORE the one you are in, in performed order, so
 *  row 2 here is what row 2 of today should be measured against. */
export function previousRows(sets, exerciseId, excludeSessionId) {
  const sessions = sessionsFor(sets, exerciseId);
  if (sessions.length === 0) return [];

  // "The one before this" has to mean before in TIME, not just "some other session". At the
  // start of a workout the open session has no completed sets yet and so does not appear
  // here at all — then the newest session on record is the right answer.
  const here = sessions.findIndex(s => s.sessionId === excludeSessionId);
  if (here === -1) return sessions[sessions.length - 1].rows;
  return here === 0 ? [] : sessions[here - 1].rows;
}

/** The band of loads this exercise has actually lived in, as a median with a wide margin.
 *  A typo of 477 for 47.7 lands far outside it; a genuinely heavy top set of a pyramid does
 *  not. Needs five logged sets before it will judge anything, and the open session is left
 *  out so today's typo cannot drag the median towards itself. */
export function loadRange(sets, exerciseId, excludeSessionId) {
  const sessions = sessionsFor(sets, exerciseId);
  const weights = [];

  for (const session of sessions) {
    if (session.sessionId === excludeSessionId) continue;
    for (const row of session.rows) {
      const weight = Number(row.weight);
      if (isFinite(weight) && weight > 0) {
        weights.push(weight);
      }
    }
  }

  if (weights.length < 5) return null;

  weights.sort((a, b) => a - b);
  const mid = Math.floor(weights.length / 2);
  const median = weights.length % 2 !== 0 ? weights[mid] : (weights[mid - 1] + weights[mid]) / 2;

  if (!isFinite(median) || median <= 0) return null;

  return { median, low: median / 4, high: median * 4 };
}

export function isOutlier(value, range) {
  if (!range) return false;
  const v = Number(value);
  if (!isFinite(v) || v <= 0) return false;
  return v < range.low || v > range.high;
}
