// series.js — time-series aggregation. Generated by qwen2.5-coder:14b (parts 1 & 2), integrated by Claude.
import { setVolume, epley1RM } from './stats.js';

export function dayKey(ts) {
  const date = new Date(ts);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function isoWeekKey(ts) {
  const date = new Date(ts);
  const day = date.getDay();
  const thursday = new Date(date);
  thursday.setDate(date.getDate() + 3 - ((day + 6) % 7));
  const isoYear = thursday.getFullYear();
  const firstThursday = new Date(isoYear, 0, 1);
  const dayOffset = firstThursday.getDay();
  const firstThursdayOfThatYear = new Date(isoYear, 0, 1 - dayOffset + (dayOffset > 4 ? 7 : 0));
  const weekNumber = 1 + Math.floor((thursday - firstThursdayOfThatYear) / 604800000);
  return `${isoYear}-W${String(weekNumber).padStart(2, '0')}`;
}

export function volumeByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = dayKey(set.at);
      const volume = setVolume(set);
      map.set(key, (map.get(key) || 0) + volume);
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function volumeByWeek(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = isoWeekKey(set.at);
      const volume = setVolume(set);
      map.set(key, (map.get(key) || 0) + volume);
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function best1RMByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = dayKey(set.at);
      const epley = epley1RM(set.weight, set.reps);
      map.set(key, Math.max(map.get(key) || 0, epley));
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function sessionsPerWeek(sessions) {
  if (!Array.isArray(sessions)) return [];
  const map = new Map();
  for (const session of sessions) {
    if (!session) continue;
    const key = isoWeekKey(session.startedAt);
    map.set(key, (map.get(key) || 0) + 1);
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function movingAverage(series, window) {
  if (!Array.isArray(series)) return [];
  if (!Number.isFinite(window) || window <= 1) {
    return series.map(({ key, value }) => ({ key, value }));
  }
  const result = [];
  for (let i = 0; i < series.length; i++) {
    let sum = series[i].value;
    let count = 1;
    for (let j = 1; j < window && i - j >= 0; j++) {
      sum += series[i - j].value;
      count++;
    }
    const average = Math.round((sum / count) * 100) / 100;
    result.push({ key: series[i].key, value: average });
  }
  return result;
}

// --- added by Claude for non-kg units (Stufe levels, timed holds) ---

/** Highest native load per day — best Stufe reached, or longest hold. */
export function maxLoadByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const w = Number(set.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, Math.max(map.get(key) || 0, w));
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

/** Sum of native load per day — total seconds held across a session's planks. */
export function loadSumByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const w = Number(set.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, (map.get(key) || 0) + w);
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}
