// series.js — time-series aggregation. Generated by qwen2.5-coder:14b (parts 1 & 2), integrated by Claude.
import { setVolume, epley1RM, counts } from './stats.js';

export function dayKey(ts) {
  const date = new Date(ts);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function isoWeekKey(ts) {
  const date = new Date(ts);
  const day = date.getDay();
  const thursday = new Date(date);
  thursday.setDate(date.getDate() + 3 - ((day + 6) % 7));
  const isoYear = thursday.getFullYear();
  const firstThursday = new Date(isoYear, 0, 1);
  const dayOffset = firstThursday.getDay();
  const firstThursdayOfThatYear = new Date(isoYear, 0, 1 - dayOffset + (dayOffset > 4 ? 7 : 0));
  const weekNumber = 1 + Math.floor((thursday - firstThursdayOfThatYear) / 604800000);
  return `${isoYear}-W${String(weekNumber).padStart(2, '0')}`;
}

export function volumeByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = dayKey(set.at);
      const volume = setVolume(set);
      map.set(key, (map.get(key) || 0) + volume);
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function volumeByWeek(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = isoWeekKey(set.at);
      const volume = setVolume(set);
      map.set(key, (map.get(key) || 0) + volume);
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function best1RMByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (set && set.done === true) {
      const key = dayKey(set.at);
      const epley = epley1RM(set.weight, set.reps);
      map.set(key, Math.max(map.get(key) || 0, epley));
    }
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function sessionsPerWeek(sessions) {
  if (!Array.isArray(sessions)) return [];
  const map = new Map();
  for (const session of sessions) {
    if (!session) continue;
    const key = isoWeekKey(session.startedAt);
    map.set(key, (map.get(key) || 0) + 1);
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

export function movingAverage(series, window) {
  if (!Array.isArray(series)) return [];
  if (!Number.isFinite(window) || window <= 1) {
    return series.map(({ key, value }) => ({ key, value }));
  }
  const result = [];
  for (let i = 0; i < series.length; i++) {
    let sum = series[i].value;
    let count = 1;
    for (let j = 1; j < window && i - j >= 0; j++) {
      sum += series[i - j].value;
      count++;
    }
    const average = Math.round((sum / count) * 100) / 100;
    result.push({ key: series[i].key, value: average });
  }
  return result;
}

// --- added by Claude for non-kg units (Stufe levels, timed holds) ---

/** Highest native load per day — best Stufe reached, or longest hold. */
export function maxLoadByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const w = Number(set.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, Math.max(map.get(key) || 0, w));
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

/** Sum of native load per day — total seconds held across a session's planks. */
export function loadSumByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const w = Number(set.weight);
    if (!Number.isFinite(w) || w <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, (map.get(key) || 0) + w);
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value: Math.round(value * 100) / 100 }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

// --- v6: bodyweight work, where reps are the only record ---

/** Best single-set rep count per day. */
export function bestRepsByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const r = Number(set.reps);
    if (!Number.isFinite(r) || r <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, Math.max(map.get(key) || 0, r));
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

/** Total reps per day — the bodyweight equivalent of volume. */
export function repsSumByDay(sets) {
  if (!Array.isArray(sets)) return [];
  const map = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const r = Number(set.reps);
    if (!Number.isFinite(r) || r <= 0) continue;
    const key = dayKey(set.at);
    map.set(key, (map.get(key) || 0) + r);
  }
  return Array.from(map.entries())
    .map(([key, value]) => ({ key, value }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

// --- per-exercise progression, bucketed by session / week / month ---
// The aggregation was generated by qwen2.5-coder:14b; Claude fixed two bugs in it (maxLoad
// called .filter() on the number Math.max returns, and each bucket kept the FIRST timestamp
// rather than the smallest, which mis-ordered weeks) and adapted it to v6's units, where a
// bodyweight set has no load at all and `counts()` decides what is countable.

export function monthKey(ts) {
  const date = new Date(ts);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  return `${year}-${month}`;
}

function bucketOf(set, bucket, sessionById) {
  let key, at;
  if (bucket === 'week') {
    key = isoWeekKey(set.at);
    at = set.at;
  } else if (bucket === 'month') {
    key = monthKey(set.at);
    at = set.at;
  } else {
    key = String(set.sessionId);
    const session = sessionById.get(set.sessionId);
    at = session && Number.isFinite(session.startedAt) ? session.startedAt : set.at;
  }
  return { key, at };
}

function labelFor(key, bucket, at) {
  if (bucket === 'week') return `KW ${key.slice(-2)}`;
  if (bucket === 'month') return new Date(at).toLocaleDateString(undefined, { month: 'short', year: 'numeric' });
  return new Date(at).toLocaleDateString(undefined, { day: '2-digit', month: 'short' });
}

export function progressSeries(sets, opts) {
  if (!Array.isArray(sets)) return [];
  const o = opts || {};
  const sessionById = Array.isArray(o.sessions)
    ? new Map(o.sessions.filter(Boolean).map((s) => [s.id, s]))
    : new Map();

  const buckets = new Map();
  for (const set of sets) {
    if (!set || set.done !== true) continue;
    const { key, at } = bucketOf(set, o.bucket, sessionById);
    if (!buckets.has(key)) buckets.set(key, { key, at, rows: [] });
    const b = buckets.get(key);
    if (Number.isFinite(at) && at < b.at) b.at = at;   // earliest moment wins, so weeks sort right
    b.rows.push(set);
  }

  const series = [];
  for (const { key, at, rows } of buckets.values()) {
    let value = 0;
    switch (o.metric) {
      case 'maxLoad':
        for (const s of rows) {
          const w = Number(s.weight);
          if (Number.isFinite(w) && w > 0 && w > value) value = w;
        }
        break;
      case 'best1rm':
        for (const s of rows) {
          if (!counts(s) || s.loadless === true) continue;
          const e = epley1RM(Number(s.weight), Number(s.reps));
          if (e > value) value = e;
        }
        break;
      case 'bestReps':
        for (const s of rows) {
          if (!counts(s)) continue;
          const r = Number(s.reps);
          if (r > value) value = r;
        }
        break;
      case 'reps':
        for (const s of rows) {
          if (!counts(s)) continue;
          const r = Number(s.reps);
          if (Number.isFinite(r) && r > 0) value += r;
        }
        break;
      case 'sets':
        for (const s of rows) if (counts(s)) value++;
        break;
      case 'nativeSum':
        for (const s of rows) {
          const w = Number(s.weight);
          if (Number.isFinite(w) && w > 0) value += w;
        }
        break;
      default:
        for (const s of rows) value += setVolume(s);
    }
    // A bucket worth 0 holds nothing countable for this metric — a session that was started
    // and never filled in, or sets ticked off with no numbers. Plotting it as a zero makes an
    // abandoned workout look like a total collapse, so it is left out entirely.
    if (value > 0) {
      series.push({ key, label: labelFor(key, o.bucket, at), value: Math.round(value * 100) / 100, at });
    }
  }

  return series.sort((a, b) => a.at - b.at);
}

export function withDeltas(series) {
  if (!Array.isArray(series)) return [];
  return series.map((entry, index) => {
    const prev = index > 0 ? series[index - 1] : null;
    const delta = prev ? Math.round((entry.value - prev.value) * 100) / 100 : null;
    const pct = prev && prev.value !== 0 ? Math.round((delta / prev.value) * 10000) / 100 : null;
    return { ...entry, delta, pct };
  });
}
