// stats.js — pure workout math. Generated by qwen2.5-coder:14b (parts 1 & 2), integrated by Claude.

function ok(x) {
  return Number.isFinite(x) && x > 0;
}

export function epley1RM(weight, reps) {
  if (!ok(weight) || !ok(reps)) return 0;
  if (reps === 1) return weight;
  return Math.round(weight * (1 + reps / 30) * 100) / 100;
}

// `kgWeight` and `loadless` are attached at load time by app.js. `kgWeight` is the set's
// load converted to kilograms via the exercise's unit (Stufe -> kg, timed holds -> 0).
// `loadless` marks a bodyweight exercise, where there is no weight to record and the rep
// count alone is the result — without it, fifteen push-ups counted as nothing at all.
export function counts(set) {
  if (!set || typeof set !== 'object' || set.done !== true) return false;
  if (!ok(set.reps)) return false;
  return set.loadless === true ? true : ok(set.weight);
}
export function setVolume(set) {
  if (typeof set !== 'object' || set === null) return 0;
  const w = Number.isFinite(set.kgWeight) ? set.kgWeight : set.weight;
  if (!ok(w) || !ok(set.reps)) return 0;
  return Math.round(w * set.reps * 100) / 100;
}

export function totalVolume(sets) {
  if (!Array.isArray(sets)) return 0;
  return Math.round(sets.reduce((total, s) => total + (s && s.done === true ? setVolume(s) : 0), 0) * 100) / 100;
}

export function personalRecords(sets) {
  if (!Array.isArray(sets)) sets = [];
  let maxWeight = 0;
  let maxReps = 0;
  let best1RM = 0;
  let bestSet = null;

  for (const set of sets) {
    if (!counts(set)) continue;
    if (set.loadless === true) {
      // no weight exists, so the best set is simply the longest run of reps
      if (set.reps > maxReps) { maxReps = set.reps; bestSet = set; }
      continue;
    }
    if (set.weight > maxWeight) maxWeight = set.weight;
    if (set.reps > maxReps) maxReps = set.reps;
    const current1RM = epley1RM(set.weight, set.reps);
    if (current1RM > best1RM) {
      best1RM = current1RM;
      bestSet = set;
    }
  }

  return { maxWeight, maxReps, best1RM, bestSet };
}

export function exerciseSummary(sets) {
  if (!Array.isArray(sets)) sets = [];
  let totalSets = 0;
  let totalReps = 0;
  let volume = 0;
  let maxWeight = 0;
  let best1RM = 0;
  const sessionIds = new Set();

  for (const set of sets) {
    if (!counts(set)) continue;
    totalSets++;
    totalReps += set.reps;
    volume += setVolume(set);
    sessionIds.add(set.sessionId);
    if (set.loadless === true) continue;
    if (set.weight > maxWeight) maxWeight = set.weight;
    const current1RM = epley1RM(set.weight, set.reps);
    if (current1RM > best1RM) best1RM = current1RM;
  }

  return {
    totalSets,
    totalReps,
    totalVolume: Math.round(volume * 100) / 100,
    maxWeight,
    best1RM,
    sessionCount: sessionIds.size,
  };
}
