// timer.js — rest countdown. Generated by qwen2.5-coder:14b (gemma4:12b and gemma4:e4b both
// failed to return this file at all: their reasoning chains exhausted the 60s bridge window).
export function createRestTimer(onChange) {
  let running = false, remaining = 0, total = 0, endsAt = 0, handle = null;

  function state() { return { running, remaining, total }; }
  function fire() { if (typeof onChange === 'function') onChange(state()); }
  function tick() {
    remaining = Math.max(0, Math.ceil((endsAt - Date.now()) / 1000));
    if (remaining === 0) { clearInterval(handle); handle = null; running = false; fire(); return; }
    fire();
  }

  return {
    state,
    start(seconds) { clearInterval(handle); total = Math.max(1, Math.round(Number(seconds) || 0)); endsAt = Date.now() + total * 1000; remaining = total; running = true; fire(); handle = setInterval(tick, 250); },
    stop() { clearInterval(handle); handle = null; running = false; remaining = 0; fire(); },
    addSeconds(s) { if (!running) return; const n = Math.round(Number(s) || 0); endsAt += n * 1000; total += n; remaining = Math.max(0, Math.ceil((endsAt - Date.now()) / 1000)); fire(); }
  };
}
