// views/exercise.js — one exercise's history and progression. Originally generated by
// qwen2.5-coder:14b; rewritten by Claude to render per unit — estimated 1RM only makes
// sense for kilograms, so Stufe shows level progression and timed holds show seconds.
import { esc, fmtDate, fmtKg, fmtVolume } from '../fmt.js';
import { exerciseSummary, personalRecords } from '../stats.js';
import { best1RMByDay, volumeByDay, maxLoadByDay, loadSumByDay } from '../series.js';
import { lineChart, barChart } from '../charts.js';
import { unitOf, formatLoad, describeSet, kgPerStufe } from '../units.js';

export function view(state) {
  const ex = state.exercises.find(e => e.id === state.route.id);
  if (!ex) return `<section class="card"><p class="muted">Exercise not found.</p></section>`;

  const sets = state.sets.filter(x => x.exerciseId === ex.id);
  const doneSets = sets.filter(x => x.done === true);
  const sum = exerciseSummary(sets);
  const pr = personalRecords(sets);
  const sessions = new Map(state.sessions.map(s => [s.id, s]));
  const u = unitOf(ex);

  // sessionCount from exerciseSummary only counts sets with valid reps, which would hide
  // the Back Extension days logged as "3x" with no reps. Count the real sessions instead.
  const sessionCount = new Set(doneSets.map(s => s.sessionId)).size;

  let html = `<section class="card"><h2>${esc(ex.name)}</h2>`
    + `<p class="muted">${esc(ex.muscleGroup || 'Other')} &middot; measured in ${esc(u.noun)}`
    + (u.id === 'stufe' ? ` (1 St. counted as ${fmtKg(kgPerStufe(ex))} kg)` : '')
    + `</p></section>`;

  // --- tiles, per unit ---
  if (u.id === 'time') {
    const best = doneSets.reduce((m, s) => Math.max(m, Number(s.weight) || 0), 0);
    const totalSecs = doneSets.reduce((t, s) => t + (Number(s.weight) || 0), 0);
    html += `<section class="tiles">`
      + `<div class="tile"><b>${fmtKg(best)} s</b><span>longest hold</span></div>`
      + `<div class="tile"><b>${doneSets.length}</b><span>holds logged</span></div>`
      + `<div class="tile"><b>${Math.round(totalSecs)} s</b><span>total time</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else if (u.id === 'stufe') {
    html += `<section class="tiles">`
      + `<div class="tile"><b>${formatLoad(pr.maxWeight, ex)}</b><span>top level</span></div>`
      + `<div class="tile"><b>${sum.totalReps}</b><span>total reps</span></div>`
      + `<div class="tile"><b>${fmtVolume(sum.totalVolume)}</b><span>volume (converted)</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else {
    html += `<section class="tiles">`
      + `<div class="tile"><b>${fmtKg(pr.best1RM)}</b><span>est. 1RM</span></div>`
      + `<div class="tile"><b>${fmtKg(pr.maxWeight)}</b><span>top weight</span></div>`
      + `<div class="tile"><b>${fmtVolume(sum.totalVolume)}</b><span>total volume</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  }

  // --- charts, per unit ---
  if (u.id === 'time') {
    html += `<section class="card"><h2>Longest hold</h2><div class="chart">${lineChart(maxLoadByDay(sets).slice(-14), { width: 340, height: 180 })}</div></section>`;
    html += `<section class="card"><h2>Total seconds per session</h2><div class="chart">${barChart(loadSumByDay(sets).slice(-12), { width: 340, height: 180, color: '#38bdf8' })}</div></section>`;
  } else if (u.id === 'stufe') {
    html += `<section class="card"><h2>Level reached</h2><div class="chart">${lineChart(maxLoadByDay(sets).slice(-14), { width: 340, height: 180 })}</div></section>`;
    html += `<section class="card"><h2>Volume per session day</h2><div class="chart">${barChart(volumeByDay(sets).slice(-12), { width: 340, height: 180, color: '#38bdf8' })}</div></section>`;
  } else {
    html += `<section class="card"><h2>Estimated 1RM</h2><div class="chart">${lineChart(best1RMByDay(sets).slice(-14), { width: 340, height: 180 })}</div></section>`;
    html += `<section class="card"><h2>Volume per session day</h2><div class="chart">${barChart(volumeByDay(sets).slice(-12), { width: 340, height: 180, color: '#38bdf8' })}</div></section>`;
  }

  html += `<section class="card"><h2>Notes</h2><textarea rows="3" data-field="exercise-notes" data-id="${ex.id}" data-focus="en-${ex.id}" placeholder="Cues, setup, niggles...">${esc(ex.notes || '')}</textarea></section>`;

  const history = Array.from(doneSets.reduce((acc, s) => {
    if (!acc.has(s.sessionId)) acc.set(s.sessionId, []);
    acc.get(s.sessionId).push(s);
    return acc;
  }, new Map()).entries())
    .sort((a, b) => ((sessions.get(b[0]) || {}).startedAt || 0) - ((sessions.get(a[0]) || {}).startedAt || 0))
    .slice(0, 14);

  html += `<section class="card"><h2>History</h2><ul class="list">`;
  if (history.length === 0) {
    html += `<li class="muted">No logged sets yet.</li>`;
  } else {
    for (const [sid, rows] of history) {
      const when = sessions.get(sid) ? sessions.get(sid).startedAt : 0;
      html += `<li><span class="li-t">${fmtDate(when)}</span>`
        + `<span class="li-s">${rows.map(r => esc(describeSet(r, ex))).join(', ')}</span></li>`;
    }
  }
  html += `</ul></section>`;

  return html;
}
