// views/exercises.js — the exercise library. Originally generated by qwen2.5-coder:14b;
// extended by Claude with a unit picker (kg / Stufe / timed hold) and a Stufe conversion field.
import { esc } from '../fmt.js';
import { UNITS, unitOf, kgPerStufe } from '../units.js';

export function view(state) {
  let html = `<section class="card"><h2>Add exercise</h2><div class="form">`
    + `<input id="ex-name" data-focus="ex-name" data-enter="add-exercise" placeholder="Exercise name" autocomplete="off">`
    + `<input id="ex-group" data-focus="ex-group" data-enter="add-exercise" placeholder="Muscle group" autocomplete="off">`
    + `<select id="ex-unit" data-focus="ex-unit" aria-label="Unit">`
    + Object.values(UNITS).map(u => `<option value="${u.id}">${esc(u.label)}</option>`).join('')
    + `</select>`
    + `<input id="ex-sets" data-focus="ex-sets" type="number" min="1" max="20" value="3" inputmode="numeric" aria-label="Default sets">`
    + `<button class="primary" data-act="add-exercise">Add</button>`
    + `</div><p class="muted">Pick <b>Stufe</b> for machines with numbered levels, or <b>Seconds held</b> for planks and other timed holds.</p></section>`;

  if (state.exercises.length === 0) {
    html += `<section class="card"><p class="muted">No exercises yet.</p></section>`;
    return html;
  }

  const grouped = new Map();
  state.exercises.forEach(ex => {
    const g = ex.muscleGroup || 'Other';
    if (!grouped.has(g)) grouped.set(g, []);
    grouped.get(g).push(ex);
  });

  Array.from(grouped.keys()).sort((a, b) => a.localeCompare(b)).forEach(group => {
    html += `<section class="card"><h2>${esc(group)}</h2><ul class="list">`;
    grouped.get(group).forEach(ex => {
      const u = unitOf(ex);
      html += `<li><a class="li-t grow" href="#/exercise/${ex.id}">${esc(ex.name)}`
        + (u.id === 'kg' ? '' : ` <span class="badge">${esc(u.short)}</span>`)
        + `</a>`
        + `<label class="mini">sets<input type="number" min="1" max="20" value="${ex.defaultSets}" data-field="default-sets" data-id="${ex.id}" data-focus="ds-${ex.id}" inputmode="numeric"></label>`
        + `<label class="mini">rest<input type="number" min="5" max="600" step="15" value="${Number(ex.restSeconds) > 0 ? Math.round(ex.restSeconds) : 120}" data-field="rest-seconds" data-id="${ex.id}" data-focus="rs-${ex.id}" inputmode="numeric">s</label>`
        + `<button class="del" data-act="delete-exercise" data-id="${ex.id}" aria-label="Delete">&times;</button></li>`;
    });
    html += `</ul></section>`;
  });

  const stufeExercises = state.exercises.filter(e => unitOf(e).id === 'stufe');
  if (stufeExercises.length) {
    html += `<section class="card"><h2>Stufe conversion</h2>`
      + `<p class="muted">Used only to fold Stufe work into your kilogram volume totals. Your logged Stufe numbers never change.</p><ul class="list">`;
    stufeExercises.forEach(ex => {
      html += `<li><span class="li-t grow">${esc(ex.name)}</span>`
        + `<label class="mini">1 St. =<input type="number" min="0.1" step="0.5" value="${kgPerStufe(ex)}" data-field="kg-per-stufe" data-id="${ex.id}" data-focus="kps-${ex.id}" inputmode="decimal">kg</label></li>`;
    });
    html += `</ul></section>`;
  }

  return html;
}
