// views/exercise.js — one exercise's history and progression. Originally generated by
// qwen2.5-coder:14b; rewritten by Claude to render per unit — estimated 1RM only makes
// sense for kilograms, so Stufe shows level progression and timed holds show seconds.
import { esc, fmtDate, fmtKg, fmtVolume } from '../fmt.js';
import { exerciseSummary, personalRecords } from '../stats.js';
import { unitOf, formatLoad, describeSet, kgPerStufe } from '../units.js';
import { exerciseProgress } from './exercise-progress.js';
import { lockAttr, disabledAttr, lockButton } from '../lock.js';
import { suggest } from '../coach.js';
import { coachBlock } from './coach-block.js';

export function view(state) {
  const ex = state.exercises.find(e => e.id === state.route.id);
  if (!ex) return `<section class="card"><p class="muted">Exercise not found.</p></section>`;

  const sets = state.sets.filter(x => x.exerciseId === ex.id);
  const doneSets = sets.filter(x => x.done === true);
  const sum = exerciseSummary(sets);
  const pr = personalRecords(sets);
  const sessions = new Map(state.sessions.map(s => [s.id, s]));
  const u = unitOf(ex);

  // sessionCount from exerciseSummary only counts sets with valid reps, which would hide
  // the Back Extension days logged as "3x" with no reps. Count the real sessions instead.
  const sessionCount = new Set(doneSets.map(s => s.sessionId)).size;

  let html = `<section class="card"><h2>${esc(ex.name)}</h2>`
    + `<p class="muted">${esc(ex.muscleGroup || 'Other')} &middot; measured in ${esc(u.noun)}`
    + (u.id === 'stufe' ? ` (1 St. counted as ${fmtKg(kgPerStufe(ex))} kg)` : '')
    + `</p></section>`;

  html += `<section class="card"><h2>Next session</h2>${coachBlock(suggest(sets, ex), ex, null)}</section>`;

  // --- tiles, per unit ---
  if (u.id === 'time') {
    const best = doneSets.reduce((m, s) => Math.max(m, Number(s.weight) || 0), 0);
    const totalSecs = doneSets.reduce((t, s) => t + (Number(s.weight) || 0), 0);
    html += `<section class="tiles">`
      + `<div class="tile"><b>${fmtKg(best)} s</b><span>longest hold</span></div>`
      + `<div class="tile"><b>${doneSets.length}</b><span>holds logged</span></div>`
      + `<div class="tile"><b>${Math.round(totalSecs)} s</b><span>total time</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else if (u.id === 'cardio') {
    const best = doneSets.reduce((m, s) => Math.max(m, Number(s.weight) || 0), 0);
    const totalMin = doneSets.reduce((t, s) => t + (Number(s.weight) || 0), 0);
    html += `<section class="tiles">`
      + `<div class="tile"><b>${fmtKg(best)} min</b><span>longest</span></div>`
      + `<div class="tile"><b>${Math.round(totalMin)} min</b><span>total time</span></div>`
      + `<div class="tile"><b>${doneSets.length}</b><span>pieces</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else if (u.id === 'body') {
    html += `<section class="tiles">`
      + `<div class="tile"><b>${pr.maxReps}</b><span>best set</span></div>`
      + `<div class="tile"><b>${sum.totalReps}</b><span>total reps</span></div>`
      + `<div class="tile"><b>${sum.totalSets}</b><span>sets logged</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else if (u.id === 'stufe') {
    html += `<section class="tiles">`
      + `<div class="tile"><b>${formatLoad(pr.maxWeight, ex)}</b><span>top level</span></div>`
      + `<div class="tile"><b>${sum.totalReps}</b><span>total reps</span></div>`
      + `<div class="tile"><b>${fmtVolume(sum.totalVolume)}</b><span>volume (converted)</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  } else {
    html += `<section class="tiles">`
      + `<div class="tile"><b>${fmtKg(pr.best1RM)}</b><span>est. 1RM</span></div>`
      + `<div class="tile"><b>${fmtKg(pr.maxWeight)}</b><span>top weight</span></div>`
      + `<div class="tile"><b>${fmtVolume(sum.totalVolume)}</b><span>total volume</span></div>`
      + `<div class="tile"><b>${sessionCount}</b><span>sessions</span></div></section>`;
  }

  // The Exercise progress panel draws these same curves and lets you switch between session,
  // week and month, so the old fixed charts that used to sit here only showed everything twice.
  html += exerciseProgress(state, ex, { showPicker: false });

  const nid = `exnotes-${ex.id}`;
  html += `<section${lockAttr(state, nid, 'card')}><div class="row"><h2 class="grow">Notes</h2>${lockButton(state, nid)}</div>`
    + `<textarea rows="3" data-field="exercise-notes" data-id="${ex.id}" data-focus="en-${ex.id}" placeholder="Cues, setup, niggles..."${disabledAttr(state, nid)}>${esc(ex.notes || '')}</textarea></section>`;

  const history = Array.from(doneSets.reduce((acc, s) => {
    if (!acc.has(s.sessionId)) acc.set(s.sessionId, []);
    acc.get(s.sessionId).push(s);
    return acc;
  }, new Map()).entries())
    .sort((a, b) => ((sessions.get(b[0]) || {}).startedAt || 0) - ((sessions.get(a[0]) || {}).startedAt || 0))
    .slice(0, 14);

  html += `<section class="card"><h2>History</h2><ul class="list history">`;
  if (history.length === 0) {
    html += `<li class="muted">No logged sets yet.</li>`;
  } else {
    for (const [sid, rows] of history) {
      const when = sessions.get(sid) ? sessions.get(sid).startedAt : 0;
      html += `<li><span class="li-t">${fmtDate(when)}</span>`
        + `<span class="li-s">${rows.map(r => esc(describeSet(r, ex))).join(', ')}</span></li>`;
    }
  }
  html += `</ul></section>`;

  return html;
}
