// views/home.js — generated by qwen2.5-coder:14b. Claude fix: it pasted the prompt's data-shape
// description into the file as literal (invalid) JS above the function; removed.
import { esc, fmtDate, fmtVolume } from '../fmt.js';
import { totalVolume } from '../stats.js';
import { isoWeekKey } from '../series.js';

export function view(state) {
  let html = '';

  const open = state.sessions.find(s => !s.endedAt);
  if (open) {
    html += `<a class="card hero" href="#/session/${open.id}"><div class="hero-t">Workout in progress</div><div class="hero-s">${esc(open.routineName)} &middot; ${fmtDate(open.startedAt)}</div></a>`;
  }

  html += `<section class="card"><h2>Start a workout</h2><div class="chips">`;
  state.routines.forEach(r => {
    html += `<button class="chip primary" data-act="start-routine" data-id="${r.id}">${esc(r.name)}</button>`;
  });
  html += `<button class="chip" data-act="start-empty">Free workout</button></div>`;
  if (state.routines.length === 0) {
    html += `<p class="muted">No routines yet. <a href="#/routines">Create one</a>.</p>`;
  }
  html += `</section>`;

  const wk = isoWeekKey(Date.now());
  const weekSessions = state.sessions.filter(s => isoWeekKey(s.startedAt) === wk);
  const ids = new Set(weekSessions.map(s => s.id));
  const weekSets = state.sets.filter(s => ids.has(s.sessionId));
  const vol = totalVolume(weekSets);
  html += `<section class="tiles"><div class="tile"><b>${weekSessions.length}</b><span>this week</span></div><div class="tile"><b>${fmtVolume(vol)}</b><span>week volume</span></div><div class="tile"><b>${state.sessions.length}</b><span>total</span></div></section>`;

  html += `<section class="card"><h2>Recent workouts</h2><ul class="list">`;
  state.sessions.slice(0, 8).forEach(s => {
    const ss = state.sets.filter(x => x.sessionId === s.id);
    const dn = ss.filter(x => x.done);
    html += `<li><a href="#/session/${s.id}"><span class="li-t">${esc(s.routineName)}</span><span class="li-s">${fmtDate(s.startedAt)} &middot; ${dn.length} sets &middot; ${fmtVolume(totalVolume(ss))}</span></a><button class="del" data-act="delete-session" data-id="${s.id}" aria-label="Delete">&times;</button></li>`;
  });
  if (state.sessions.length === 0) {
    html += `<li class="muted">Nothing logged yet.</li>`;
  }
  html += `</ul></section>`;

  return html;
}
