// views/progress.js — generated by qwen2.5-coder:14b, unmodified.
import { esc, fmtKg, fmtVolume } from '../fmt.js';
import { totalVolume, personalRecords } from '../stats.js';
import { volumeByWeek, sessionsPerWeek, movingAverage } from '../series.js';
import { lineChart, barChart } from '../charts.js';
import { unitOf } from '../units.js';

export function view(state) {
  const sets = state.sets;
  const weeks = volumeByWeek(sets).slice(-12);
  const perWeek = sessionsPerWeek(state.sessions).slice(-12);
  const trend = movingAverage(weeks, 3);

  const leaderboard = state.exercises.filter(ex => unitOf(ex).e1rm).map(ex => {
    const rows = sets.filter(x => x.exerciseId === ex.id);
    const pr = personalRecords(rows);
    const vol = totalVolume(rows);
    return { ex, pr, vol };
  }).filter(e => e.pr.best1RM > 0)
    .sort((a, b) => b.pr.best1RM - a.pr.best1RM)
    .slice(0, 8);

  return `
    <section class="tiles">
      <div class="tile"><b>${state.sessions.length}</b><span>workouts</span></div>
      <div class="tile"><b>${fmtVolume(totalVolume(sets))}</b><span>lifetime volume</span></div>
      <div class="tile"><b>${sets.filter(s => s.done === true).length}</b><span>sets logged</span></div>
    </section>

    <section class="card"><h2>Weekly volume</h2><div class="chart">${barChart(weeks, { width: 340, height: 190 })}</div></section>

    <section class="card"><h2>Volume trend, 3 week average</h2><div class="chart">${lineChart(trend, { width: 340, height: 190, color: '#22c55e' })}</div></section>

    <section class="card"><h2>Workouts per week</h2><div class="chart">${barChart(perWeek, { width: 340, height: 160, color: '#f59e0b' })}</div></section>

    <section class="card"><h2>Top lifts</h2><ul class="list">
      ${leaderboard.length > 0 ? leaderboard.map(e => `
        <li><a class="li-t grow" href="#/exercise/${e.ex.id}">${esc(e.ex.name)}</a><span class="li-s">${fmtKg(e.pr.best1RM)} kg est. 1RM &middot; ${fmtVolume(e.vol)}</span></li>
      `).join('') : '<li class="muted">Log a few sets to see your top lifts.</li>'}
    </ul></section>

    <section class="card"><h2>Backup</h2>
      <p class="muted">Your data lives in this browser, tied to this exact web address — it does not follow you to a different one. Export before changing where the app is hosted, and now and then anyway.</p>
      <div class="form">
        <button class="primary" data-act="export-backup">Export backup</button>
        <button class="ghost" data-act="pick-backup">Restore backup</button>
        <input type="file" id="backup-file" data-field="backup-file" accept="application/json,.json" hidden>
      </div>
      <h2 style="margin-top:14px">Danger zone</h2>
      <div class="form"><button class="ghost danger" data-act="reset-all">Reset everything</button></div>
    </section>
  `;
}
