// views/routines.js — originally generated by qwen2.5-coder:14b.
//
// v6: picking exercises used to have no end. The chips toggled live and the card stayed a
// wall of buttons forever, so there was never a moment where the routine felt finished.
// Now a routine is either being edited — chips, with a Done button — or settled, showing
// the exercises it contains. Creating one drops you straight into editing it.
import { esc } from '../fmt.js';
import { unitOf } from '../units.js';

export function view(state) {
  let html = `<section class="card"><h2>New routine</h2><div class="form form-stack">`
    + `<input id="routine-name" data-focus="routine-name" data-enter="add-routine" placeholder="Push day" autocomplete="off">`
    + `<button class="primary wide" data-act="add-routine">Create routine</button>`
    + `</div></section>`;

  html += `<section class="card"><h2>Import a routine</h2>`
    + `<p class="muted">Loads a routine file — a plan from your gym, for instance. Exercises are matched by name and reused, so nothing already in your library changes and importing twice adds nothing twice.</p>`
    + `<div class="form"><button class="ghost" data-act="pick-routine-file">Choose a routine file</button>`
    + `<input type="file" id="routine-file" data-field="routine-file" accept="application/json,.json" hidden></div></section>`;

  if (state.routines.length === 0) {
    html += `<section class="card"><p class="muted">No routines yet. Create one above, import one, then pick the exercises it contains.</p></section>`;
  }

  const byId = new Map(state.exercises.map(e => [e.id, e]));

  for (const r of state.routines) {
    const picked = Array.isArray(r.exerciseIds) ? r.exerciseIds : [];
    const editing = state.editingRoutine === r.id;

    html += `<section class="card"><div class="row"><h2 class="grow">${esc(r.name)}</h2>`
      + `<span class="muted">${picked.length} exercise${picked.length === 1 ? '' : 's'}</span>`
      + `<button class="del" data-act="delete-routine" data-id="${r.id}" aria-label="Delete">&times;</button></div>`;

    if (editing) {
      html += `<p class="muted">Tap to add or remove. Press Done when the routine is complete.</p><div class="chips">`;
      for (const ex of state.exercises) {
        const on = picked.includes(ex.id);
        const u = unitOf(ex);
        html += `<button class="${on ? 'chip on' : 'chip'}" data-act="routine-toggle-exercise" data-id="${r.id}" data-eid="${ex.id}">`
          + `${esc(ex.name)}${u.id === 'kg' ? '' : ` <span class="badge">${esc(u.short || u.label)}</span>`}</button>`;
      }
      html += `</div><div class="form"><button class="primary wide" data-act="done-routine">Done</button></div>`;
    } else {
      if (picked.length === 0) {
        html += `<p class="muted">No exercises yet.</p>`;
      } else {
        // The list order IS the order you do them in — a workout started from this routine
        // adds its exercises in exactly this sequence — so it has to be rearrangeable.
        // Arrows rather than dragging: a drag gesture on a phone fights with scrolling, which
        // is the very problem the locked input fields were added to solve.
        html += `<ul class="list">`;
        picked.forEach((eid, i) => {
          const ex = byId.get(eid);
          html += `<li><span class="li-t grow">${esc(ex ? ex.name : 'Removed exercise')}</span>`
            + `<span class="li-s">${esc(ex ? unitOf(ex).label : '')}</span>`
            + `<button class="ghost move" data-act="routine-move" data-id="${r.id}" data-i="${i}" data-d="-1"`
            + `${i === 0 ? ' disabled' : ''} aria-label="Move up">&uarr;</button>`
            + `<button class="ghost move" data-act="routine-move" data-id="${r.id}" data-i="${i}" data-d="1"`
            + `${i === picked.length - 1 ? ' disabled' : ''} aria-label="Move down">&darr;</button></li>`;
        });
        html += `</ul>`;
      }
      html += `<div class="form"><button class="ghost" data-act="edit-routine" data-id="${r.id}">Edit exercises</button></div>`;
    }

    html += `</section>`;
  }

  return html;
}
