// views/routines.js — generated by qwen2.5-coder:14b, unmodified.
import { esc } from '../fmt.js';

export function view(state) {
  let html = `<section class="card"><h2>New routine</h2><div class="form"><input id="routine-name" data-focus="routine-name" data-enter="add-routine" placeholder="Push day" autocomplete="off"><button class="primary" data-act="add-routine">Create</button></div></section>`;

  if (state.routines.length === 0) {
    html += `<section class="card"><p class="muted">No routines yet. Create one above, then tap exercises to add them.</p></section>`;
  }

  for (const r of state.routines) {
    const picked = Array.isArray(r.exerciseIds) ? r.exerciseIds : [];
    html += `<section class="card"><div class="row"><h2 class="grow">${esc(r.name)}</h2><span class="muted">${picked.length} exercises</span><button class="del" data-act="delete-routine" data-id="${r.id}" aria-label="Delete">&times;</button></div><div class="chips">`;

    for (const ex of state.exercises) {
      const cls = picked.includes(ex.id) ? 'chip on' : 'chip';
      html += `<button class="${cls}" data-act="routine-toggle-exercise" data-id="${r.id}" data-eid="${ex.id}">${esc(ex.name)}</button>`;
    }

    html += `</div></section>`;
  }

  return html;
}
