// views/session.js — the active workout screen. Originally generated by qwen2.5-coder:14b
// (in two calls); extended by Claude so each exercise renders in its own unit: kg, Stufe,
// or a timed hold with no rep column at all.
import { esc, fmtDateTime, fmtVolume, clock } from '../fmt.js';
import { totalVolume } from '../stats.js';
import { unitOf, formatLoad } from '../units.js';
import { suggest } from '../coach.js';
import { coachBlock } from './coach-block.js';
import { previousRows, loadRange, isOutlier } from '../history.js';
import { lockAttr, disabledAttr, lockButton } from '../lock.js';

/** "+2.5 kg", "−1 reps", "±0 reps" — only once there is something to compare. */
function chip(now, then, label) {
  const a = Number(now);
  const b = Number(then);
  if (!Number.isFinite(a) || a <= 0 || !Number.isFinite(b) || b <= 0) return '';
  const d = Math.round((a - b) * 100) / 100;
  const cls = d > 0 ? 'up' : d < 0 ? 'down' : 'same';
  const sign = d > 0 ? '+' : d < 0 ? '−' : '±';
  return `<span class="dlt ${cls}">${sign}${Math.abs(d)} ${esc(label)}</span>`;
}

function block(state, session, eid, ex, rows, tip, prev, range) {
  const lid = `ex-${eid}`;
  const off = disabledAttr(state, lid);
  const name = ex ? ex.name : 'Removed exercise';
  const u = unitOf(ex);
  const loadLabel = u.short;

  // A box you have not filled in yet stays EMPTY, with last time's number as a grey ghost.
  // It used to be pre-filled with 0, so every entry meant clearing a zero first.
  const num = (v) => (Number.isFinite(Number(v)) && Number(v) > 0 ? String(Number(v)) : '');

  const body = rows.map((r, i) => {
    // The ghost, the comparison line and the coach all line up on the SAME set number: row 3
    // today is measured against row 3 of the last session, never against that session's
    // heaviest set. That is the whole point when the load changes from set to set.
    const p = prev[i] || null;
    const wPh = num(p && p.weight) || '–';
    const rPh = num(p && p.reps) || '–';

    // Bodyweight work has nothing to put in a load box, so it does not get one.
    const load = u.hasLoad
      ? `<td><input type="number" step="${u.step}" min="0" inputmode="decimal" value="${num(r.weight)}" placeholder="${esc(wPh)}" data-field="weight" data-id="${r.id}" data-focus="w-${r.id}"${off} aria-label="${esc(u.label)}"></td><td class="unit">${esc(loadLabel)}</td>`
      : `<td colspan="2" class="unit bw">bodyweight</td>`;
    const reps = u.hasReps
      ? `<td><input type="number" step="1" min="0" inputmode="numeric" value="${num(r.reps)}" data-field="reps" data-id="${r.id}" data-focus="p-${r.id}"${off} aria-label="Reps" placeholder="${esc(rPh)}"></td><td class="unit">reps</td>`
      : `<td colspan="2"></td>`;

    const bad = u.hasLoad && isOutlier(r.weight, range);
    const main = `<tr class="${r.done ? 'done' : ''}${bad ? ' outlier' : ''}"><td class="idx">${i + 1}</td>${load}${reps}`
      + `<td><button class="check${r.done ? ' on' : ''}" data-act="toggle-done" data-id="${r.id}" aria-label="Done">&#10003;</button></td>`
      + `<td><button class="del" data-act="remove-set" data-id="${r.id}" aria-label="Remove set">&times;</button></td></tr>`;

    // What this same set did last time, and how far today is from it.
    let line = '';
    if (p) {
      const was = [];
      if (u.hasLoad && num(p.weight)) was.push(formatLoad(p.weight, ex));
      if (u.hasReps && num(p.reps)) was.push(`${Number(p.reps)} reps`);
      if (was.length) {
        line += `<span class="prev-was">last: ${esc(was.join(' × '))}</span>`;
        if (u.hasLoad) line += chip(r.weight, p.weight, loadLabel);
        if (u.hasReps) line += chip(r.reps, p.reps, 'reps');
      }
    }
    if (bad) line += `<span class="dlt bad">check this number</span>`;
    const extra = line ? `<tr class="prevrow"><td></td><td colspan="6" class="prev">${line}</td></tr>` : '';

    return main + extra;
  }).join('');

  // Volume in kilograms is meaningless for a plank, a row or a set of push-ups, so each
  // unit summarises itself in the terms it is actually measured in.
  const done = rows.filter(r => r.done);
  const sum = (f) => done.reduce((t, r) => t + (Number(f(r)) || 0), 0);
  const summary =
      u.id === 'time'   ? `${done.length} hold${done.length === 1 ? '' : 's'}`
    : u.id === 'cardio' ? `${Math.round(sum(r => r.weight))} min`
    : u.id === 'body'   ? `${Math.round(sum(r => r.reps))} reps`
    : fmtVolume(totalVolume(rows));

  return `<section${lockAttr(state, lid, 'card ex')}><div class="row"><h2 class="grow"><a href="#/exercise/${eid}">${esc(name)}</a></h2><span class="muted">${summary}</span>${lockButton(state, lid)}</div>`
    + (tip || '')
    + `<table class="sets"><tbody>${body}</tbody></table>`
    + `<button class="ghost" data-act="add-set" data-sid="${session.id}" data-eid="${eid}">+ Add set</button></section>`;
}

export function view(state) {
  const s = state.sessions.find(x => x.id === state.route.id);
  if (!s) return `<section class="card"><p class="muted">Workout not found.</p></section>`;
  const sets = state.sets.filter(x => x.sessionId === s.id);
  const byId = new Map(state.exercises.map(e => [e.id, e]));
  let order = Array.isArray(s.exerciseIds) && s.exerciseIds.length ? s.exerciseIds.slice() : [];
  for (const x of sets) if (!order.includes(x.exerciseId)) order.push(x.exerciseId);
  const doneCount = sets.filter(x => x.done).length;

  let html = `<section class="card"><div class="row"><h2 class="grow">${esc(s.routineName)}</h2>`
    + (s.endedAt ? `<span class="muted">finished</span>` : `<button class="primary" data-act="finish-session" data-id="${s.id}">Finish</button>`)
    + `</div><p class="muted">${fmtDateTime(s.startedAt)} &middot; ${doneCount}/${sets.length} sets done &middot; ${fmtVolume(totalVolume(sets))}</p></section>`;

  if (!s.endedAt && !(state.ui && state.ui.unlockedId)) {
    html += `<p class="lockhint">Fields are locked while you scroll — tap an exercise to edit it.</p>`;
  }

  if (state.rest.running) {
    html += `<div class="rest live"><b>${clock(state.rest.remaining)}</b><button class="ghost" data-act="rest-add" data-secs="30">+30s</button><button class="ghost" data-act="rest-stop">Stop</button></div>`;
  } else {
    html += `<div class="rest"><span class="muted">Rest</span><button class="ghost" data-act="rest-start" data-secs="60">60s</button><button class="ghost" data-act="rest-start" data-secs="90">90s</button><button class="ghost" data-act="rest-start" data-secs="120">2:00</button><button class="ghost" data-act="rest-start" data-secs="180">3:00</button></div>`;
  }

  for (const eid of order) {
    const ex = byId.get(eid);
    // The advice is for THIS session, so it must look only at what came before it —
    // feeding today's half-finished sets back in would have the coach chase its own tail.
    const history = state.sets.filter(x => x.exerciseId === eid && x.sessionId !== s.id);
    const tip = s.endedAt ? '' : coachBlock(suggest(history, ex), ex, { sessionId: s.id, exerciseId: eid });
    // Last time's sets, in the order they were numbered. This used to be a single row picked
    // as `history[history.length - 1]`, which is whatever IndexedDB happened to return last —
    // set ids are random, so the "last set" shown was effectively a random one.
    const prev = previousRows(state.sets, eid, s.id);
    // The plausible band for this exercise, worked out from history only, so a number typed
    // today cannot widen the band that is meant to catch it.
    const range = loadRange(state.sets, eid, s.id);
    html += block(state, s, eid, ex, sets.filter(x => x.exerciseId === eid), tip, prev, range);
  }

  html += `<section class="card"><div class="form"><select id="session-add-select">`
    + state.exercises.map(e => `<option value="${e.id}">${esc(e.name)}</option>`).join('')
    + `</select><button class="primary" data-act="session-add-exercise" data-sid="${s.id}">Add exercise</button></div></section>`;

  const nid = `notes-${s.id}`;
  html += `<section${lockAttr(state, nid, 'card')}><div class="row"><h2 class="grow">Notes</h2>${lockButton(state, nid)}</div>`
    + `<textarea rows="3" data-field="session-notes" data-id="${s.id}" data-focus="n-${s.id}" placeholder="How did it go?"${disabledAttr(state, nid)}>${esc(s.notes || '')}</textarea></section>`;

  return html;
}
