// views/session.js — the active workout screen. Originally generated by qwen2.5-coder:14b
// (in two calls); extended by Claude so each exercise renders in its own unit: kg, Stufe,
// or a timed hold with no rep column at all.
import { esc, fmtDateTime, fmtVolume, clock } from '../fmt.js';
import { totalVolume } from '../stats.js';
import { unitOf } from '../units.js';
import { suggest } from '../coach.js';
import { coachBlock } from './coach-block.js';

function block(session, eid, ex, rows, tip) {
  const name = ex ? ex.name : 'Removed exercise';
  const u = unitOf(ex);
  const loadLabel = u.short;

  const body = rows.map((r, i) => {
    const load = `<td><input type="number" step="${u.step}" min="0" inputmode="decimal" value="${r.weight}" data-field="weight" data-id="${r.id}" data-focus="w-${r.id}" aria-label="${esc(u.label)}"></td><td class="unit">${esc(loadLabel)}</td>`;
    const reps = u.hasReps
      ? `<td><input type="number" step="1" min="0" inputmode="numeric" value="${r.reps == null ? '' : r.reps}" data-field="reps" data-id="${r.id}" data-focus="p-${r.id}" aria-label="Reps" placeholder="–"></td><td class="unit">reps</td>`
      : `<td colspan="2"></td>`;
    return `<tr class="${r.done ? 'done' : ''}"><td class="idx">${i + 1}</td>${load}${reps}`
      + `<td><button class="check${r.done ? ' on' : ''}" data-act="toggle-done" data-id="${r.id}" aria-label="Done">&#10003;</button></td>`
      + `<td><button class="del" data-act="remove-set" data-id="${r.id}" aria-label="Remove set">&times;</button></td></tr>`;
  }).join('');

  const vol = totalVolume(rows);
  const summary = u.id === 'time'
    ? `${rows.filter(r => r.done).length} holds`
    : fmtVolume(vol);

  return `<section class="card ex"><div class="row"><h2 class="grow"><a href="#/exercise/${eid}">${esc(name)}</a></h2><span class="muted">${summary}</span></div>`
    + (tip || '')
    + `<table class="sets"><tbody>${body}</tbody></table>`
    + `<button class="ghost" data-act="add-set" data-sid="${session.id}" data-eid="${eid}">+ Add set</button></section>`;
}

export function view(state) {
  const s = state.sessions.find(x => x.id === state.route.id);
  if (!s) return `<section class="card"><p class="muted">Workout not found.</p></section>`;
  const sets = state.sets.filter(x => x.sessionId === s.id);
  const byId = new Map(state.exercises.map(e => [e.id, e]));
  let order = Array.isArray(s.exerciseIds) && s.exerciseIds.length ? s.exerciseIds.slice() : [];
  for (const x of sets) if (!order.includes(x.exerciseId)) order.push(x.exerciseId);
  const doneCount = sets.filter(x => x.done).length;

  let html = `<section class="card"><div class="row"><h2 class="grow">${esc(s.routineName)}</h2>`
    + (s.endedAt ? `<span class="muted">finished</span>` : `<button class="primary" data-act="finish-session" data-id="${s.id}">Finish</button>`)
    + `</div><p class="muted">${fmtDateTime(s.startedAt)} &middot; ${doneCount}/${sets.length} sets done &middot; ${fmtVolume(totalVolume(sets))}</p></section>`;

  if (state.rest.running) {
    html += `<div class="rest live"><b>${clock(state.rest.remaining)}</b><button class="ghost" data-act="rest-add" data-secs="30">+30s</button><button class="ghost" data-act="rest-stop">Stop</button></div>`;
  } else {
    html += `<div class="rest"><span class="muted">Rest</span><button class="ghost" data-act="rest-start" data-secs="60">60s</button><button class="ghost" data-act="rest-start" data-secs="90">90s</button><button class="ghost" data-act="rest-start" data-secs="120">2:00</button><button class="ghost" data-act="rest-start" data-secs="180">3:00</button></div>`;
  }

  for (const eid of order) {
    const ex = byId.get(eid);
    // The advice is for THIS session, so it must look only at what came before it —
    // feeding today's half-finished sets back in would have the coach chase its own tail.
    const history = state.sets.filter(x => x.exerciseId === eid && x.sessionId !== s.id);
    const tip = s.endedAt ? '' : coachBlock(suggest(history, ex), ex, { sessionId: s.id, exerciseId: eid });
    html += block(s, eid, ex, sets.filter(x => x.exerciseId === eid), tip);
  }

  html += `<section class="card"><div class="form"><select id="session-add-select">`
    + state.exercises.map(e => `<option value="${e.id}">${esc(e.name)}</option>`).join('')
    + `</select><button class="primary" data-act="session-add-exercise" data-sid="${s.id}">Add exercise</button></div></section>`;

  html += `<section class="card"><h2>Notes</h2><textarea rows="3" data-field="session-notes" data-id="${s.id}" data-focus="n-${s.id}" placeholder="How did it go?">${esc(s.notes || '')}</textarea></section>`;

  return html;
}
